### ISSUE TITLE
./build.sh --update-pkg-repo rust-1.38.0 compile error

### ISSUE THREAD

**Issue by sreekupm** [Augustin-FL/building-pfsense-iso-from-source#1]
Dear Augustin, 

I am trying to build but getting error unable to build rust. 
see the log 

-- Installing: /wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/bin/llvm-diff
-- Installing: /wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/bin/llvm-dis
-- Installing: /wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/bin/llvm-dwarfdump
-- Installing: /wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/bin/llvm-dwp
*** Signal 9

Stop.
make: stopped in /usr/ports/lang/rust
-- Installing: /wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/bin/llvm-elfabi
-- Installing: /wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/bin/llvm-exegesis
-- Installing: /wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/bin/llvm-extract
-- Installing: /wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/bin/llvm-jitlink
=>> Cleaning up wrkdir
-- Installing: /wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/bin/llvm-link
-- Installing: /wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/bin/llvm-lipo
-- Installing: /wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/bin/llvm-lto2
===>  Cleaning for rust-1.38.0
-- Installing: /wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/bin/llvm-mc
-- Installing: /wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/bin/llvm-mca
CMake Error at tools/llvm-mca/cmake_install.cmake:36 (file):
  file INSTALL cannot copy file
  "/wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/build/bin/llvm-mca"
  to
  "/wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/bin/llvm-mca".
Call Stack (most recent call first):
  tools/cmake_install.cmake:76 (include)
  cmake_install.cmake:63 (include)

gmake[1]: *** [Makefile:62: install] Error 1
gmake[1]: Leaving directory '/wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/build/x86_64-unknown-freebsd/llvm/build'
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /wrkdirs/usr/ports/lang/rust/work/rustc-1.38.0-src/vendor/cmake/src/lib.rs:813:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
	finished in 6526.926
build of lang/rust | rust-1.38.0 ended at Sat Oct 19 23:05:10 IST 2019
build time: 02:29:55
!!! build failure encountered !!!

**Comment by Augustin-FL** [comment]
```
*** Signal 9

Stop.
```

Your program got killed using a SIGKILL signal. This may happen when you don't have enough RAM. 

In order to preserve itself and avoid putting the system at risk, FreeBSD can kill programs that are asking too much memory. This mechanism is called OOM Killer (Out of Memory Killer)

rust needs a lot of memory when compiling, so your error makes sense 

How many RAM are you having ?

You could try restarting building ports. if that still fails, you will need to either consider RAM upgrade or disable packages that are needing rust 

Does this reply your question ?

**Comment by sreekupm** [comment]
Dear Augustin,
**Thanks for your support issue solved !!** 

started with 4 GB ram, now increased to 10 GB. now its working fine. 


Thanks
