### ISSUE TITLE
Unable to access file /root/MyFirewall/tmp/stage-dir/share/MyFirewall/fix_for_SA-19-10.ufs:No such file or directory

### ISSUE THREAD

**Issue by sreekupm** [Augustin-FL/building-pfsense-iso-from-source#10]
Dear Augustin,

The issue is still pending, please support me . :(

====>> Copying metadata for package rc
====>> Creating core package rc
pkg: Unable to access file /usr/MyFirewall/tmp/stage-dir/share/MyFirewall/fix_for_SA-19-10.ufs:No such file or directory
pkg: cannot load keyword from /usr/ports/Keywords/shell.ucl: No such file or directory
pkg: unknown keyword shell: @shell
====>> ERROR: Execution of 'pkg create -o /usr/MyFirewall/tmp/MyFirewall_MyFirewall_2_5_amd64-core/.real_20191113-2128/All -p /tmp/rc.4yZobsv/rc_plist -r /usr/MyFirewall/tmp/stage-dir -m /tmp/rc.4yZobsv/rc_metadir' failed (rc = 70)
====>> Removing immutable flags from /tmp/rc.4yZobsv
====>> Removing recursively /tmp/rc.4yZobsv

####################################
Something went wrong, check errors!
####################################

**Comment by sreekupm** [comment]
What's inside the folder /root/pfsense/tmp/stage-dir/share/ --> share folder is not exist.

what's the content of /root/pfsense/src/usr/local/share/ --> 2 Folders locale and MyFirewall

**Comment by Augustin-FL** [comment]
i would advice you to run ```/root/build.sh --clean-builder``` then ```/root/build.sh --skip-final-rsync iso``` again?

**Comment by sreekupm** [comment]
Same Error :(

**Comment by sreekupm** [comment]
Dear Augustin, 
started from scratch more than 10 times, the error is almost same 
pkg: Unable to access file **/usr/MyFirewall/tmp/stage-dir/usr/local/share/MyFirewall/fix_for_SA-19-10.ufs**:No such file or directory

/usr/MyFirewall/tmp/stage-dir/usr/local/share/MyFirewall folder is available but inside the folder 
base.mtree
base.txz
MyFirewall-repo.conf

Also another pfsense folder is available in the same location 
/usr/MyFirewall/tmp/stage-dir/usr/local/share/pfsense
inside the folder required file is available 
fix_for_SA-19-10.ufs
iso_3166-1_list_en.xml
folder ssl
folder keys
folder ascii-art

Pfsense repository  ==  pfsense/pfsense master branch. 

any idea about the error

**Comment by sreekupm** [comment]
build ISO successfully

**Comment by Augustin-FL** [comment]
could you please share here the steps you have done / the part that wasn't clear, so that I can update the documentation?

**Comment by sreekupm** [comment]
Dear Augustin,

I have built ISO. after that I have install the same ISO but the GUI is not working 

I have started from scratch, 

I will update entire steps after building

**Comment by sreekupm** [comment]
Install packages 
pkg install -y pkg vim nano
pkg install -y git nginx poudriere-devel mkfile rsync sudo
pkg install -y vmdktool curl qemu-user-static gtar xmlstarlet pkgconf openssl111
pkg install -y htop screen wget
pkg install -y open-vm-tools
portsnap fetch extract

mkdir -p /root/sign/
cd /root/sign/
openssl genrsa -out repo.key 2048
chmod 0400 repo.key
openssl rsa -in repo.key -out repo.pub -pubout
printf "function: sha256\nfingerprint: `sha256 -q repo.pub`\n" > fingerprint

####################################
/root/sign/sign.sh
##############
#!/bin/sh
read -t 2 sum
[ -z "$sum" ] && exit 1
echo SIGNATURE
echo -n $sum | openssl dgst -sign /root/sign/repo.key -sha256 -binary
echo
echo CERT
cat /root/sign/repo.pub
echo END
##############################################################################
chmod +x /root/sign/sign.sh
cd /root
git clone https://github.com/sreekupm/pfsense.git
cd pfsense
git checkout RELENG_2_5_0
set pfSense_gui_branch=2_5_0
set pfSense_port_branch=v2_5_0
set product_name=Myfirewall

mv src/usr/local/share/pfSense src/usr/local/share/${product_name}
rm src/usr/local/share/${product_name}/keys/pkg/trusted/*
cp /root/sign/fingerprint src/usr/local/share/${product_name}/keys/pkg/trusted/fingerprint

###################
Build.conf
###################
export PRODUCT_NAME="Myfirewall"
export FREEBSD_REPO_BASE=https://github.com/sreekupm/FreeBSD-src.git # Location of your FreeBSD sources repository
export POUDRIERE_PORTS_GIT_URL=https://github.com/sreekupm/FreeBSD-ports.git # Location your FreeBSD ports repository

export FREEBSD_BRANCH=RELENG_2_5_0 # Branch of FreeBSD sources to build
# The branch of FreeBSD ports to build is set automatically based on pfSense GUI branch.
# If you would like to build a specific branch of FreeBSD ports, the variable to set is POUDRIERE_PORTS_GIT_BRANCH

# Netgate support creation of staging builds (pre-dev, nonpublic version)
unset USE_PKG_REPO_STAGING # This disable staging build
# The kind of ISO that will be built (stable or development) is defined in src/etc/version in pfSense GUI repo

export DEFAULT_ARCH_LIST="amd64.amd64" # We only want to build an x64 ISO, we don't care of ARM versions

# Signing key
export PKG_REPO_SIGNING_COMMAND="/root/sign/sign.sh ${PKG_REPO_SIGN_KEY}"

# This command retrieves the IP address of the first network interface
export myIPAddress=$(ifconfig -a | grep inet | head -1 | cut -d ' ' -f 2)

export PKG_REPO_SERVER_DEVEL="pkg+http://${myIPAddress}/packages"
export PKG_REPO_SERVER_RELEASE="pkg+http://${myIPAddress}/packages"

export PKG_REPO_SERVER_STAGING="pkg+http://${myIPAddress}/packages" # We need to also specify this variable, because even
# if we don't build staging release some ports configuration is made for staging.
#####################################################################################################################################


./build.sh --setup-poudriere

set pfSense_gui_branch=v2_5_0
set pfSense_port_branch=devel
set product_name=Myfirewall


cd /usr/local/www/nginx/
rm -rf *
mkdir -p packages
# PKG web server for core PKG repositories (pfSense-base, pfSense-rc, etc...)
ln -s /root/pfsense/tmp/${product_name}_${pfSense_gui_branch}_amd64-core/.latest packages/${product_name}_${pfSense_gui_branch}_amd64-core
# PKG web server for other PKG repositories
ln -s /usr/local/poudriere/data/packages/${product_name}_${pfSense_gui_branch}_amd64-${product_name}_${pfSense_port_branch} packages/${product_name}_${pfSense_gui_branch}_amd64-${product_name}_${pfSense_port_branch} 
# Web server for monitoring ports build
ln -s /usr/local/poudriere/data/logs/bulk/${product_name}_${pfSense_gui_branch}_amd64-${product_name}_${pfSense_port_branch}/latest poudriere

# Allow directory indexing, and configure nginx to start automatically on boot
sed -i '' 's+/usr/local/www/nginx;+/usr/local/www/nginx; autoindex on;+g' /usr/local/etc/nginx/nginx.conf
echo nginx_enable=\"YES\" >> /etc/rc.conf
service nginx restart

./build.sh --update-pkg-repo

set pfSense_gui_branch=v2_5_0
set pfSense_port_branch=devel
set product_name=Myfirewall

./build.sh --skip-final-rsync iso

/usr/local/poudriere/data/packages/nocgate_master_amd64-nocgate_devel

These are the steps 
but i faced one issue in the below lines 


ln -s /root/pfsense/tmp/${product_name}_${pfSense_gui_branch}_amd64-core/.latest packages/${product_name}_${pfSense_gui_branch}_amd64-core
# PKG web server for other PKG repositories
ln -s /usr/local/poudriere/data/packages/${product_name}_${pfSense_gui_branch}_amd64-${product_name}_${pfSense_port_branch} packages/${product_name}_${pfSense_gui_branch}_amd64-${product_name}_${pfSense_port_branch} 
# Web server for monitoring ports build
ln -s /usr/local/poudriere/data/logs/bulk/${product_name}_${pfSense_gui_branch}_amd64-${product_name}_${pfSense_port_branch}/latest poudriere

**Comment by sreekupm** [comment]
Links are not worked for me, I have changed the link before ./build.sh --skip-final-rsync iso

After install new ISO WEB GUI is not working :(

**Comment by Augustin-FL** [comment]
I understand. but what's the error? did you check nginx logs on the pfSense?

**Comment by sreekupm** [comment]
Nginx.log 

:( 

Dec  1 15:38:32 pfSense nginx: 192.168.1.30 - - [01/Dec/2019:15:38:32 +0000] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03\x9B\xAD\x82\xA0.\xE1\xE1\x9F\xB6\x07\xD77Q..\xBE\x1FRb\x00O\x98\x98(\xF1\x9E\xE5\x01\x84\xFD_? \x1F\xCDr\xCF\x08hw\x13\xCDmb%_|\xFEx\xE1\xB2,V\xE3\x1E8`Q\x0F\xEF18g\xC6\xF1\x00\x22\x9A\x9A\x13\x01\x13\x02\x13\x03\xC0+\xC0/\xC0,\xC00\xCC\xA9\xCC\xA8\xC0\x13\xC0\x14\x00\x9C\x00\x9D\x00/\x005\x00" 400 150 "-" "-"
Dec  1 15:38:32 pfSense nginx: 192.168.1.30 - - [01/Dec/2019:15:38:32 +0000] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03\xB7\x9A~!\x7F\xB1h\xF7Ve\x0C\xB6\xEA\xD8!8\x87\xA7P\xC8\x0B\x07\xF7\x1BF\x9D\x16\xDEM\x90\xC3\xE2 :\xED\xD4\x0E\xDB\xB8X\x08M^\xDD\x14\xBBV\x95%5\xD7\xA1\x15\x02\xBF\xBF\xAA\x07\x93\xD4\x00!\xAA\xF0\x1B\x00\x22\xAA\xAA\x13\x01\x13\x02\x13\x03\xC0+\xC0/\xC0,\xC00\xCC\xA9\xCC\xA8\xC0\x13\xC0\x14\x00\x9C\x00\x9D\x00/\x005\x00" 400 150 "-" "-"

**Comment by cdotsasa** [comment]
@sreekupm How you adjusted the links?
