### ISSUE TITLE
After Building ISO GUI is not working 

### ISSUE THREAD

**Issue by sreekupm** [Augustin-FL/building-pfsense-iso-from-source#11]
Dear Augustin,

After Building the ISO. GUI is not working please help.

**Comment by sreekupm** [comment]
Dear Augustin,

Please find the error page. 

any idea about this 

![image](https://user-images.githubusercontent.com/14277199/69914119-5bf19480-1466-11ea-90bf-eb577222ef78.png)

**Comment by aruntr8** [comment]
Dear Augustin, 
The same error occurred for me... after successfully build ISO,  installed it in a VM,  when accessing  web Gui it showing "this site can't provide a secure connection"
log entries  in system.log

pfsense php[293]: rc.bootup: Creating SSL Certificate for this host
Dec  7 07:53:20 pfSense kernel: done.
Dec  7 07:53:20 pfSense php[293]: rc.bootup: Error creating WebGUI Certificate: openssl library returns: error:0E06D06C:configuration file routines:NCONF_get_string:no value
Dec  7 07:53:20 pfSense php[293]: rc.bootup: Error creating WebGUI Certificate: openssl library returns: error:0E06D06C:configuration file routines:NCONF_get_string:no value
Dec  7 07:53:21 pfSense kernel: done.

**Comment by Augustin-FL** [comment]
```pfsense php[293]: rc.bootup: Creating SSL Certificate for this host```

@aruntr8 @sreekupm It may sounds stupid but..did you tried to reboot ?
it seems like the SSL creation wasn't accepted by nginx

I don't know why this happens to you...actually I could login normally after generating an ISO
Did you try the [What to do when you are locked out from GUI](https://docs.netgate.com/pfsense/en/latest/book/config/what-to-do-when-locked-out-of-the-webgui.html#http-vs-https-confusion) advices?

**Comment by sreekupm** [comment]
Dear Augustin,
this is the error in syslog. 
Please help to resolve the same. 

Dec 20 09:50:00 pfSense php[293]: rc.bootup: Error creating WebGUI Certificate: openssl library returns: error:0E06D06C:configuration file routines:NCONF_get_string:no value
Dec 20 09:50:00 pfSense php[293]: rc.bootup: Error creating WebGUI Certificate: openssl library returns: error:0E06D06C:configuration file routines:NCONF_get_string:no value
Dec 20 09:50:01 pfSense kernel: done.

**Comment by Augustin-FL** [comment]
???
DId you read my previous comment?
You are not replying to the question i've asked...

**Comment by sreekupm** [comment]
After rebooting, same issue

**Comment by Augustin-FL** [comment]
I found the root cause : after build, the file [openssl.cnf](https://github.com/pfsense/pfsense/blob/master/src/usr/local/share/pfSense/ssl/openssl.cnf) is not properly included in the ISO.

The build scripts seems to use the ```.cnf``` which is in the build server ```/etc``` folder, instead of using the one from github.

Manually running ```curl -o "/etc/ssl/openssl.cnf" "https://raw.githubusercontent.com/pfsense/pfsense/master/src/usr/local/share/pfSense/ssl/openssl.cnf"``` then rebooting the server seems to fix the issue.

**Comment by sreekupm** [comment]
I have  copied the ssl folder from a working machine then it is working fine. 
How can we resolve the issue?

**Comment by sreekupm** [comment]
Dear Augstin, 

I have Replaced the FreeBSD-src/crypto/openssl/apps/openssl.cnf
Now its working fine. But I don't know this is the correct way. Please suggest and update the file in https://github.com/pfsense/FreeBSD-src/crypto/openssl/apps/openssl.cnf

**Comment by Augustin-FL** [comment]
Setting up [$g['product_name']](https://github.com/pfsense/pfsense/blob/master/src/etc/inc/globals.inc#L66) to the name of your ISO (instead of "pfSense") seems to completly fix the issue 

I will update the guidelines accordingly
