### ISSUE TITLE
make: cannot open /usr/ports/Mk/bsd.port.mk

### ISSUE THREAD

**Issue by LCHOICEzz** [Augustin-FL/building-pfsense-iso-from-source#14]
Hello Augustin-FL
I try to follow your steps. 

When I execute **./build.sh --update-pkg-repo**,
I meet this problem:
**make: cannot open /usr/ports/Mk/bsd.port.mk.
[00:00:01] Error: Error looking up pre-build ports vars**

I have tried to re-execute **portsnap fetch extract** and add privilege to /usr/ports/Mk/bsd.port.mk
The result is same as I have met. 

So could you help me solve this problem? 

Thanks!

**Comment by Augustin-FL** [comment]
```portsnap fetch extract``` is a prerequisite and is part of the things you need to do _before_ starting the build

I am not sure of what happens when you try to execute portsnap in the middle of the build...I guess you have to re-create or update the jail accordingly ?

you should restart the build from the beginning (ie, reinstall freeBSD then start over)

**Comment by LCHOICEzz** [comment]
> `portsnap fetch extract` is a prerequisite and is part of the things you need to do _before_ starting the build
> 
> I am not sure of what happens when you try to execute portsnap in the middle of the build...I guess you have to re-create or update the jail accordingly ?
> 
> you should restart the build from the beginning (ie, reinstall freeBSD then start over)

Thank you very much. I have solved this problem through re-execute portsnap fetch extract. 
However, I can not find any RELENG_2_5_0 in github.com/pfsense/pfsense and the same as FreeBSD-ports. 
Could you help me to solve this problem?

**Comment by Augustin-FL** [comment]
> This guide has been written for 2.5.0 (which does not exist yet)

as far as I am aware of, 2.5.0 is not planned for release yet.  Netgate changed their plans last week (they decided to roll out a 2.4.5 release before 2.5.0). please see #13 for details
