### ISSUE TITLE
./build.sh --update-pkg-repo problems

### ISSUE THREAD

**Issue by LCHOICEzz** [Augustin-FL/building-pfsense-iso-from-source#15]
Hello, recently I meet anthor problems. 

When I execute **./build.sh --update-pkg-repo**, it tells :

**Finished security/clamav | clamav-0.102.1,1: Failed: fetch**
**Finished textproc/flex | flex-2.6.4_1: Failed: fetch/runaway**
**Finished devel/protobuf | protobuf-3.9.2,1: Failed: fetch/runaway**

I think these problems are same. Could you help me?
Thanks!

**Comment by Augustin-FL** [comment]
well...without the individual logs of each port I cant do much...
could you give the actual logs of one of the ports ?

**Comment by Augustin-FL** [comment]
could you give me the logs of any failing port?

**Comment by Augustin-FL** [comment]
closing because lack of details
