### ISSUE TITLE
inaccurate text in README.md

### ISSUE THREAD

**Issue by gonzopancho** [Augustin-FL/building-pfsense-iso-from-source#16]
> Netgate doesn't allow you to build a product using the name "pfSense" (because of copyright/trademark). 

It's trademark, not copyright.

**Comment by Augustin-FL** [comment]
hi

Thanks! Sorry for that mistake. I will update the text..

Don't hesitate to tell me if you see any other issue 

Also, If you want to contact me privately for any reason, Jim-P knows my email (because I contacted security@netgate.com few weeks ago).
