### ISSUE TITLE
Revised renaming of pfSense

### ISSUE THREAD

**Issue by rschell** [Augustin-FL/building-pfsense-iso-from-source#18]
I submitted a PR to eliminate the need to manually rename a number of pfSense files in the ports repo.  Those should no longer be necessary, might check to make sure the wiki is updated to match the current pfsense master.

**Comment by sreekupm** [comment]
Dear Ronald, 
Can you update here the changes? 
I have an error on pfsense-upgrade and pfsense-repo while update package repo. 

Please help me.

**Comment by Augustin-FL** [comment]
Thanks rshell ! 

I removed the step asking to rename things in FreeBSD-Ports.

I've also included the update of `make.conf` in this wiki in order to reflect rbgarga comments on https://github.com/pfsense/FreeBSD-ports/pull/747
