### ISSUE TITLE
Fetch timeout

### ISSUE THREAD

**Issue by LCHOICEzz** [Augustin-FL/building-pfsense-iso-from-source#19]
Hello! This is my third questions. Thank you very much.
Recently, I execute ./build.sh --update-pkg-repo, but the result seems failed.
Now I am in China, you know we have GFW, and it limits access to some website and speeds down to some websites, like github.com  or ftpmirror.gnu.org.

So I failed to build these ports 

"ports":{"failed":[{"origin":"sysutils/libreSense-upgrade","pkgname":"pfSense-upgrade-0.67","phase":"stage","errortype":"install_error","elapsed":"2"},{"origin":"devel/readline","pkgname":"readline-8.0.0","phase":"fetch/runaway","errortype":"runaway_process","elapsed":"7202"},{"origin":"textproc/libxml2","pkgname":"libxml2-2.9.9","phase":"fetch/runaway","errortype":"runaway_process","elapsed":"7201"},{"origin":"devel/swig30","pkgname":"swig30-3.0.12","phase":"fetch/runaway","errortype":"runaway_process","elapsed":"7201"},{"origin":"devel/protobuf","pkgname":"protobuf-3.9.2,1","phase":"fetch/runaway","errortype":"runaway_process","elapsed":"7201"},{"origin":"math/gmp","pkgname":"gmp-6.1.2_1","phase":"fetch/runaway","errortype":"runaway_process","elapsed":"7201"},{"origin":"archivers/libmspack","pkgname":"libmspack-0.9.1","phase":"fetch/runaway","errortype":"runaway_process","elapsed":"7202"},{"origin":"sysutils/screen","pkgname":"screen-4.6.2_3","phase":"fetch/runaway","errortype":"runaway_process","elapsed":"7202"}],

Above all are failed logs.

This is /usr/local/poudriere/data/logs/bulk/libreSense_v2_4_5_amd64-libreSense_v2_4_5/2020-01-01_00h24m01s/logs/screen-4.6.2_3.log
=> Attempting to fetch http://xmlsoft.org/sources/libxml2-2.9.9.tar.gz
libxml2-2.9.9.tar.gz                          =>> Killing runaway build after 7200 seconds with no output
=>> Cleaning up wrkdir
===>  Cleaning for libxml2-2.9.9
Killed
build of textproc/libxml2 | libxml2-2.9.9 ended at Wed Jan  1 02:42:58 CST 2020
build time: 02:00:23
!!! build failure encountered !!!

So could you help me to solve this problem? 
Thanks!

**Comment by Augustin-FL** [comment]
Hum...That's sad 😢 

I'm not sure how to answer here....There is multiple solutions to your  problem but none of them are actually very satisfying.

- You could spawn an AWS instance outside China and install [v2ray](https://github.com/v2ray/v2ray-core) on it....or you could [get Lantern](https://github.com/getlantern/download). 

- You could manually download all files that are slowed down by the GFW, using dedicated tools for slow connections ([FDM](https://www.freedownloadmanager.org/) for instance). Once you got all files locally, you could create a new folder on your build server, and update the nginx config so that this folder is accessible using HTTP. Finally, you may update your `/etc/hosts` to make domains like xmlsoft.org point to `127.0.0.1` ...

**Comment by LCHOICEzz** [comment]
Thank you very much. I find a VPS naming Vultr. And I choose FreeBSD12.0,  FreeBSD-src FreeBSD-ports and Pfsense are all RELENG_2_4_5. I found two errors.

First, when I execute .**/build.sh --setup-poudriere** , it gives me these messages :
>>> Renaming product ports on libreSense_v2_4_5... sed: /usr/local/poudriere/ports/libreSense_v2_4_5/net-mgmt/libreSense-pkg-zabbix-agent42/pkg-descr: No such file or directory
sed: /usr/local/poudriere/ports/libreSense_v2_4_5/net-mgmt/libreSense-pkg-zabbix-proxy44/pkg-descr: No such file or directory
sed: /usr/local/poudriere/ports/libreSense_v2_4_5/net-mgmt/libreSense-pkg-zabbix-agent44/pkg-descr: No such file or directory
sed: /usr/local/poudriere/ports/libreSense_v2_4_5/net-mgmt/libreSense-pkg-zabbix-proxy4/pkg-descr: No such file or directory
sed: /usr/local/poudriere/ports/libreSense_v2_4_5/net-mgmt/libreSense-pkg-zabbix-proxy42/pkg-descr: No such file or directory
sed: /usr/local/poudriere/ports/libreSense_v2_4_5/net-mgmt/libreSense-pkg-zabbix-agent4/pkg-descr: No such file or directory
Done!

Secondly, when I execute **./build.sh --update-pkg-repo**,  it failed, beacause  two ports cannot build successfully.

boost-lib-1.72.0:
Killed
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1

Stop.
make: stopped in /usr/ports/devel/boost-libs
=>> Cleaning up wrkdir
===>  Cleaning for boost-libs-1.72.0
build of devel/boost-libs | boost-libs-1.72.0 ended at Fri Jan 17 21:07:40 CST 2020
build time: 00:07:45
!!! build failure encountered !!!

rust-1.40.0:
Caused by:
  process didn't exit successfully: `/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/bootstrap/debug/rustc --edition=2018 --crate-name syntax src/libsyntax/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=2 -C debuginfo=0 -C metadata=437980caa7b05ab1 -C extra-filename=-437980caa7b05ab1 --out-dir /wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0-rustc/x86_64-unknown-freebsd/release/deps --target x86_64-unknown-freebsd -C linker=cc -L dependency=/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0-rustc/x86_64-unknown-freebsd/release/deps -L dependency=/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0-rustc/release/deps --extern bitflags=/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0-rustc/x86_64-unknown-freebsd/release/deps/libbitflags-fddd46c7f1b5ef0f.rmeta --extern lazy_static=/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0-rustc/x86_64-unknown-freebsd/release/deps/liblazy_static-d6266cc192f51f51.rmeta --extern log=/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0-rustc/x86_64-unknown-freebsd/release/deps/liblog-fe14873d6248909e.rmeta --extern rustc_data_structures=/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0-rustc/x86_64-unknown-freebsd/release/deps/librustc_data_structures-bc5397f88ce86e88.rmeta --extern errors=/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0-rustc/x86_64-unknown-freebsd/release/deps/librustc_errors-f02a4cc83cba2e54.rmeta --extern rustc_index=/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0-rustc/x86_64-unknown-freebsd/release/deps/librustc_index-b5e09b7e8b97a662.rmeta --extern rustc_lexer=/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0-rustc/x86_64-unknown-freebsd/release/deps/librustc_lexer-3f34d59d274ff637.rmeta --extern rustc_target=/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0-rustc/x86_64-unknown-freebsd/release/deps/librustc_target-12a860a1b4b1354b.rmeta --extern scoped_tls=/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0-rustc/x86_64-unknown-freebsd/release/deps/libscoped_tls-a5b034b829c1fc9a.rmeta --extern rustc_serialize=/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0-rustc/x86_64-unknown-freebsd/release/deps/libserialize-4ab6cfa43872779a.rmeta --extern smallvec=/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0-rustc/x86_64-unknown-freebsd/release/deps/libsmallvec-bfe74ab465533897.rmeta --extern syntax_pos=/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0-rustc/x86_64-unknown-freebsd/release/deps/libsyntax_pos-a762f2462cfcd050.rmeta --cfg=bootstrap -Zexternal-macro-backtrace '-Clink-args=-Wl,-rpath,$ORIGIN/../lib' -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings -Zunstable-options '-Wrustc::internal' -Cprefer-dynamic -Zbinary-dep-depinfo` (signal: 9, SIGKILL: kill)
command did not execute successfully: "/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage0/bin/cargo" "build" "-Zconfig-profile" "--target" "x86_64-unknown-freebsd" "-Zbinary-dep-depinfo" "-j" "2" "-v" "--release" "--frozen" "--features" "" "--manifest-path" "/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/src/rustc/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
Traceback (most recent call last):
  File "/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/x.py", line 11, in <module>
    bootstrap.main()
  File "/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/src/bootstrap/bootstrap.py", line 909, in main
    bootstrap(help_triggered)
  File "/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/src/bootstrap/bootstrap.py", line 895, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/src/bootstrap/bootstrap.py", line 141, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /wrkdirs/usr/ports/lang/rust/work/rustc-1.40.0-src/build/bootstrap/debug/bootstrap build --config ./config.toml --jobs 2
*** Error code 1

Stop.
make: stopped in /usr/ports/lang/rust
=>> Cleaning up wrkdir
===>  Cleaning for rust-1.40.0
build of lang/rust | rust-1.40.0 ended at Fri Jan 17 21:07:51 CST 2020
build time: 00:21:53
!!! build failure encountered !!!

**Comment by Augustin-FL** [comment]
`(signal: 9, SIGKILL: kill)`

Please see #1

**Comment by LCHOICEzz** [comment]
Thank you very much! 
I build it successfully, and I want to translate your guide to Chinese, and help more people to build pfsense by themselves.

![image](https://user-images.githubusercontent.com/21484379/72660740-b6da4d80-3a0c-11ea-90cc-4af6861c3c68.png)
