### ISSUE TITLE
./build.sh --skip-final-rsync iso Error Building and installing crypto tools and athstats for amd64 architecture

### ISSUE THREAD

**Issue by sreekupm** [Augustin-FL/building-pfsense-iso-from-source#2]
Dear Augustin,

Please help on the below error.

>>> Building and installing crypto tools and athstats for amd64 architecture... (Starting - Sun Oct 20 18:18:23 IST 2019)
Something went wrong, check errors!
Terminated

-------------------------------------------------------------------------
**Log** 
----------
[0m[1m/root/MyFirewall/tmp/obj/root/MyFirewall/tmp/FreeBSD-src/amd64.amd64/tmp/usr/include/openssl/ossl_typ.h:80:16: [0m[0;1;30mnote: [0mforward declaration of 'struct bignum_st'[0m
typedef struct bignum_st BIGNUM;
[0;1;32m               ^
[0m[1m/root/MyFirewall/tmp/FreeBSD-src/tools/tools/crypto/cryptokeytest.c:147:25: [0m[0;1;35mwarning: [0m[1massigning to 'caddr_t' (aka 'char *') from 'u_int8_t *' (aka 'unsigned char *')
      converts between pointers to integer types with different sign [-Wpointer-sign][0m
        kop.crk_param[0].crp_p = ale;
[0;1;32m                               ^ ~~~
[0m[1m/root/MyFirewall/tmp/FreeBSD-src/tools/tools/crypto/cryptokeytest.c:149:25: [0m[0;1;35mwarning: [0m[1massigning to 'caddr_t' (aka 'char *') from 'u_int8_t *' (aka 'unsigned char *')
      converts between pointers to integer types with different sign [-Wpointer-sign][0m
        kop.crk_param[1].crp_p = ble;
[0;1;32m                               ^ ~~~
[0m[1m/root/MyFirewall/tmp/FreeBSD-src/tools/tools/crypto/cryptokeytest.c:151:25: [0m[0;1;35mwarning: [0m[1massigning to 'caddr_t' (aka 'char *') from 'u_int8_t *' (aka 'unsigned char *')
      converts between pointers to integer types with different sign [-Wpointer-sign][0m
        kop.crk_param[2].crp_p = cle;
[0;1;32m                               ^ ~~~
[0m[1m/root/MyFirewall/tmp/FreeBSD-src/tools/tools/crypto/cryptokeytest.c:153:25: [0m[0;1;35mwarning: [0m[1massigning to 'caddr_t' (aka 'char *') from 'u_int8_t *' (aka 'unsigned char *')
      converts between pointers to integer types with different sign [-Wpointer-sign][0m
        kop.crk_param[3].crp_p = cle;
[0;1;32m                               ^ ~~~
[0m4 warnings and 2 errors generated.
*** Error code 1

Stop.
make[1]: stopped in /root/MyFirewall/tmp/FreeBSD-src/tools/tools/crypto
*** Error code 1

Stop.
make: stopped in /root/MyFirewall/tmp/FreeBSD-src/tools/tools/crypto

**Comment by Augustin-FL** [comment]
As explained in the tutorial :

- Edit the file `/tools/tools/crypto/Makefile` : remove `cryptokeytest` from the `PROGS` command

**Comment by sreekupm** [comment]
Dear Augustin,
forgot to remove cryptokeytest. 
now working fine 
Thanks for your timely support
