### ISSUE TITLE
Built error for sysutils/cloakSense-repo ( productname: cloakSense)

### ISSUE THREAD

**Issue by cklee288** [Augustin-FL/building-pfsense-iso-from-source#20]
Hi,

I need some help on ports built. I managed to get all built (500+) built successfully using instruction provided. But, there is an error for "Building for cloakSense-repo-2.4.4_8
sed: /wrkdirs/usr/ports/sysutils/cloakSense-repo/work/cloakSense-repo-2.4.4/pfSense-repo-245.conf: No such file or directory" while building sysutils/cloakSense-repo.
             I can't figure out which part missing. Could you able to guide me through? log message as attached.
[cloakSense-repo-2.4.4_8 (2).log](https://github.com/Augustin-FL/building-pfsense-iso-from-source/files/4150974/cloakSense-repo-2.4.4_8.2.log)

**Comment by cklee288** [comment]
my fork github and using RELENG_2_4_4

cd /root
git clone https://github.com/cklee288/pfsense.git
cd pfsense
git checkout RELENG_2_4_4

**Comment by cklee288** [comment]
I found the issue. managed to fix.

**Comment by nkbali** [comment]
Hi,

Please share the resolution?
