### ISSUE TITLE
Please clarify purpose of removing cryptokeytest

### ISSUE THREAD

**Issue by dyeske** [Augustin-FL/building-pfsense-iso-from-source#22]
Please clarify the purpose of removing cryptokeytest in this commit.

[https://github.com/Augustin-FL/building-pfsense-iso-from-source/commit/f669cf8a50651fef79a145769934050d53db918b](url)

**Comment by Augustin-FL** [comment]
If you don't remove it, you end up with errors during kernel build.

These errors are related to differences between libraries ```openssl``` and ```openssl111```.

**Comment by Augustin-FL** [comment]
Can i close this issue ?
