### ISSUE TITLE
Make update changes 

### ISSUE THREAD

**Issue by BillRizer** [Augustin-FL/building-pfsense-iso-from-source#23]
hello, 
After completing the build and the entire environment, how can I create updates? (system -> update)?
currently I do:
create my change in the GUI (add widget in www / widgets)
commit git
up version PORTREVISION in sysutils / libreSense-repo / Makefile
./build.sh iso
./build.sh --update-pkg-repo
./build.sh --rsync-repos

everything goes up to the server correctly, but it is not displayed when I update through the interface, only when I do "pkg upgrade -f"

Do you know if I'm forgetting something?

thank you very much for the tudorial :)

**Comment by Augustin-FL** [comment]
Well,

I am not sure exactly what caused your issue. I tried to reproduce (using DISTVERSION and not  PORTREVISION, but that should be the same...) and i got the update message as expected 

![image](https://user-images.githubusercontent.com/9406403/80321759-fd1b2600-881f-11ea-8505-99c7b4d2f7a7.png)

pfSense GUI is internally calling [`/usr/local/sbin/libreSense-upgrade -c`](https://github.com/pfsense/pfsense/blob/master/src/etc/inc/pkg-utils.inc#L1266) (which itself is calling `pkg_static` to check/compare the version of core packages `libreSense-base` and `libreSense-kernel-libreSense` with the one avaliable on the web server).

I'm guessing that you simply hit the cache ? (there is [an internal cache](https://github.com/pfsense/pfsense/blob/master/src/etc/inc/pkg-utils.inc#L1257) on the GUI)

Another possiblity may be that you are using PORTREVISION. When running ```./build.sh --update-pkg-repo```, pfSense is performing some update ([using `sed` command](https://github.com/pfsense/pfsense/blob/master/tools/builder_common.sh#L1875-L1882) ) to the Makefile of `libreSense-repo` package. Did you ensure that this update does not interfere with your version bump?

**Comment by Augustin-FL** [comment]
Can i close this issue?
