### ISSUE TITLE
pre-installed packages

### ISSUE THREAD

**Issue by mehdiimrzz** [Augustin-FL/building-pfsense-iso-from-source#29]
Hi,

Thanks for your detailed tutorial

I've build my pfSense without any problem

Now I want to build a version embedded with some packages ( like Squid ) 

Do you have any idea how I can do that?

**Comment by sreekumarpm** [comment]
Dear mehdiimrzz ,

try to add here. 

FreeBSD-ports/security/pfSense/Makefile

**Comment by mehdiimrzz** [comment]
Thank you @SreekumarPM

**Comment by sreekumarpm** [comment]
@mehdiimrzz 

Please share the changes you made. 

It will help other people.
