### ISSUE TITLE
./build.sh --skip-final-rsync iso KERNCONF=MyFirewall buildkernel' failed (rc = 2) Error 

### ISSUE THREAD

**Issue by sreekupm** [Augustin-FL/building-pfsense-iso-from-source#3]
Dear Augustin, 

Getting Error :( Please help 

>>> Building MyFirewall kernel.
>>> Sun Oct 20 20:13:59 IST 2019 - Starting build kernel for amd64 architecture...
====>> Building kernel (MyFirewall)
make[1]: "/root/MyFirewall/tmp/FreeBSD-src/Makefile.inc1" line 343: SYSTEM_COMPILER: libclang will be built for bootstrapping a cross-compiler.
make[1]: "/root/MyFirewall/tmp/FreeBSD-src/Makefile.inc1" line 346: SYSTEM_LINKER: Determined that LD=ld matches the source tree.  Not bootstrapping a cross-linker.
make[1]: "/root/MyFirewall/tmp/FreeBSD-src/Makefile.inc1" line 1526: Missing KERNCONF /root/MyFirewall/tmp/FreeBSD-src/sys/amd64/conf/MyFirewall
--- buildkernel ---
*** [buildkernel] Error code 1

make: stopped in /root/MyFirewall/tmp/FreeBSD-src
.ERROR_TARGET='buildkernel'
.ERROR_META_FILE=''
.MAKE.LEVEL='0'
MAKEFILE=''
.MAKE.MODE='normal'
_ERROR_CMD='.PHONY'
.CURDIR='/root/MyFirewall/tmp/FreeBSD-src'
.MAKE='make'
.OBJDIR='/root/MyFirewall/tmp/obj/root/MyFirewall/tmp/FreeBSD-src/amd64.amd64'
.TARGETS='buildkernel'
DESTDIR=''
LD_LIBRARY_PATH=''
MACHINE='amd64'
MACHINE_ARCH='amd64'
MAKEOBJDIRPREFIX=''
MAKESYSPATH='/root/MyFirewall/tmp/FreeBSD-src/share/mk'
MAKE_VERSION='20180512'
PATH='/sbin:/bin:/usr/sbin:/usr/bin'
SRCTOP='/root/MyFirewall/tmp/FreeBSD-src'
OBJTOP='/root/MyFirewall/tmp/obj/root/MyFirewall/tmp/FreeBSD-src/amd64.amd64'
1 error

make: stopped in /root/MyFirewall/tmp/FreeBSD-src
.ERROR_TARGET='buildkernel'
.ERROR_META_FILE=''
.MAKE.LEVEL='0'
MAKEFILE=''
.MAKE.MODE='normal'
_ERROR_CMD='.PHONY'
.CURDIR='/root/MyFirewall/tmp/FreeBSD-src'
.MAKE='make'
.OBJDIR='/root/MyFirewall/tmp/obj/root/MyFirewall/tmp/FreeBSD-src/amd64.amd64'
.TARGETS='buildkernel'
DESTDIR=''
LD_LIBRARY_PATH=''
MACHINE='amd64'
MACHINE_ARCH='amd64'
MAKEOBJDIRPREFIX=''
MAKESYSPATH='/root/MyFirewall/tmp/FreeBSD-src/share/mk'
MAKE_VERSION='20180512'
PATH='/sbin:/bin:/usr/sbin:/usr/bin'
SRCTOP='/root/MyFirewall/tmp/FreeBSD-src'
OBJTOP='/root/MyFirewall/tmp/obj/root/MyFirewall/tmp/FreeBSD-src/amd64.amd64'
====>> ERROR: Execution of 'make -C /root/MyFirewall/tmp/FreeBSD-src -s -j6 KERNCONF=MyFirewall buildkernel' failed (rc = 2)

**Comment by Augustin-FL** [comment]
hello,

could you please read carefully 
https://github.com/Augustin-FL/building-pfsense-iso-from-source/blob/master/README.md#freebsd-source ? thanks

This error is due to a bad renaming

**Comment by tajummal-lab** [comment]
i just run the command to build kernal and iso the line stuck at freeBSD cloning
when i press ctrl+t showing me the following info
load: 0.69 cmd: git-remote-https 958 [select] 4676.21r  14.00u 147.01a 2% 11001k
what does it means???
and how much time it will take to complete the process??
![Capture](https://user-images.githubusercontent.com/56956553/67665556-c016c980-f98b-11e9-8d70-2b3a4a281b4a.PNG)

**Comment by sreekupm** [comment]
which command you running ?

**Comment by Augustin-FL** [comment]
> i just run the command to build kernal and iso the line stuck at freeBSD cloning

this mean that you have a slow internet connection...or possibly that you messed up with the URL in build.conf

> when i press ctrl+t showing me the following info
> load: 0.69 cmd: git-remote-https 958 [select] 4676.21r 14.00u 147.01a 2% 11001k
> what does it means???

it mean that your computer is currently cloning the repository 
for more information on SIGINFO(ctrl+t), please check [here](https://blog.danielisz.org/2018/06/21/the-power-of-ctrlt/)

**Comment by sreekupm** [comment]
can you explain what you are done ?
