### ISSUE TITLE
Error in ./build.sh --skip-final-rsync iso

### ISSUE THREAD

**Issue by amf75** [Augustin-FL/building-pfsense-iso-from-source#32]
Hello ,
first of all thank you for this guide.  In this final step i'll receive a strange error.
Opening /root/pfsense/logs/install_pkg_install_ports.txt

Bootstrapping pkg from pkg+http://10.6.75.198/packages/exoSphere_master_amd64-exoSphere_master, please wait...
pkg: Error fetching http://10.6.75.198/packages/exoSphere_master_amd64-exoSphere_master/Latest/pkg.txz: Not Found
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.
Bootstrapping pkg from pkg+http://10.6.75.198/packages/exoSphere_master_amd64-exoSphere_master, please wait...
pkg: Error fetching http://10.6.75.198/packages/exoSphere_master_amd64-exoSphere_master/Latest/pkg.txz: Not Found
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.
Bootstrapping pkg from pkg+http://10.6.75.198/packages/exoSphere_master_amd64-exoSphere_master, please wait...
pkg: Error fetching http://10.6.75.198/packages/exoSphere_master_amd64-exoSphere_master/Latest/pkg.txz: Not Found
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.

On server console:
installing build ports (packages) in chroot (/root/pfsense/tmp/stage-dir)... Failed!

Obviously in my local repository i have:
http://10.6.75.198/packages/exoSphere_v2_4_5_amd64-exoSphere_v_2_4_5 (v2_4_5 and not master!)

I changed everything pointed out in the guide. Since in an old issue the problem could be name files i check it again, but nothing changed. Compiled different times but i wasn't able to resolve. I don't know why it search for "..master.."  and not for branch "v2_4_5".

I'm compiling on FreeBSD 11.4 for my pfsense version 2_4_5.
Same error on FreeBSD 12.1 for my pfsense version 2_4_5.
Virtual machine 16 CPU 16 GB RAM 300 GB HDD Space

I can't understand where i go wrong.
Thanks in advance

Alessandro

**Comment by amf75** [comment]
Maybe I "solved" it with a little trick, that is by copying the symbolic link (in /usr/local/www/nginx/package) and then creating one with the version and one with the master. Practically
exoSphere_master_amd64-exoSphere_master -> /usr/local/poudriere/data/packages/exoSphere_v2_4_5_amd64-exoSphere_v2_4_5
exoSphere_v2_4_5_amd64-core -> /root/pfsense/tmp/exoSphere_v2_4_5_amd64-core/.latest
exoSphere_v2_4_5_amd64-exoSphere_v2_4_5 -> /usr/local/poudriere/data/packages/exoSphere_v2_4_5_amd64-exoSphere_v2_4_5

Even if there is some error but i try to use the iso. I keep you informed.
This was a work around, i'd like to understand the reason for a pure clear build!

thanks

Alessandro

**Comment by amf75** [comment]
The build, works, even if pfsense is written everywhere and only in some little place is exoSphere.. I think there is still a lot of works to do!

Thanks
Alessandro

**Comment by Augustin-FL** [comment]
Indeeed, it was a symbolic link issue ( [I think you forgot to replace libresense by exosphere in your setup](https://github.com/Augustin-FL/building-pfsense-iso-from-source#make-some-configurations-on-the-build-server) ? )

Can i close this issue now?

**Comment by amf75** [comment]
Yes it was a symbolic link issue but I'm sure enough I didn't forget to replace libraSense with exoSphere (to be 100% sure, in these days, i'll compile with libraSense directly, to avoid any change).
If you want you can close, in case i'll open a new one.
Another little hint i ask, can you suggest me, if you know, ho to change the brand directly in compilng phase? Witch file are direct involved? 
Thanks a lot, you are very kind!
Alessandro

**Comment by Augustin-FL** [comment]
> how to change the brand directly in compilng phase? Witch file are direct involved?

It's not that simple...there is references of pfsense everywhere in the code (from the [boot logo](https://github.com/pfsense/FreeBSD-src/blob/devel-12/stand/lua/brand-pfSense.lua) to the [files](https://github.com/pfsense/pfsense/blob/master/src/usr/local/www/js/pfSense.js) and [functions](https://github.com/pfsense/pfsense/blob/79e269c9f2002f780d2fd141595a1cec1683bb12/src/etc/inc/xmlrpc_client.inc#L25) names).

Some services(bug reporter, acb, etc...) have also some kind of interconnection with Netgate infra and therefore are specific to pfsense, there is no way to migrate them.

**Comment by amf75** [comment]
Sorry for "witch" it was a "Which" (as you correctly understood). :)
Yeah i understand. I don't wanna use other people code as mine, the pfsense and connection with netgate is due and all the credits are theirs. But i'd like to build a derivate like ubuntu from debian (where the world debian and the connection with the original linux os is not completly disappeared for common parts, sure not in the early versions ). 
My goals is to build a my own version of pfsense, like opnsense for example, derivated from pfsense but with my brand and "security point of view" and for market porpose.
I'll investigate further.
If you want and there are not other useful tips for now, you can close this ticket. 
In case i'll open another one.
Thank you for your preciuos support.
Your guide teached me a lot of things! Thanks very very much!
Alessandro
