### ISSUE TITLE
PKG_REPO_SIGN_KEY

### ISSUE THREAD

**Issue by molavvani** [Augustin-FL/building-pfsense-iso-from-source#33]
hi 
what is PKG_REPO_SIGN_KEY?
when I enter this by export PKG_REPO_SIGNING_COMMAND="/root/sign/sign.sh ${PKG_REPO_SIGN_KEY}"
in freebsd
freebsd tell me PKG_REPO_SIGN_KEY is undefined varrieble

**Comment by Augustin-FL** [comment]
Hi, 

As explained in the tutorial, you don't have to enter this command in the terminal. Instead,  you have to create a file called `build.conf` that contains this line .

If you are interested anyway, PKG_REPO_SIGN_KEY is defined here :
https://github.com/pfsense/pfsense/blob/051a5f352dd71837fc6165b4b70c91ae6a3b3271/tools/builder_defaults.sh#L298

**Comment by Augustin-FL** [comment]
can I close this issue?
