### ISSUE TITLE
Question: Suggestion on Development Environment for html/php/js

### ISSUE THREAD

**Issue by Hillsie** [Augustin-FL/building-pfsense-iso-from-source#35]
@Augustin-FL , 
Firstly, thanks for this "xxxsense" github documentation. It's been very helpful.  

Are you able help me with suggestions on how I could setup a web development environment to work on the web gui of xxxsense?

My setup has a VM with QEMU/KVM.  Instead of pulling in the repo directly into the VM,  I thought I would try share the web repository from the host to the guest VM. The idea is that I would manage the web development on the host and then see the changes on the guest via the web browser. I think I have reached my limit on how to go about this. Secondly, I am not sure  what needs to be built to do this?

Any suggestions, or creative ideas would be appreciated.

**Comment by Augustin-FL** [comment]
Well, Netgate is using a [patch module](https://pfsense-docs.readthedocs.io/en/latest/development/system-patches.html) to test & apply temporarily some changes. You can generate a patch with the patch/git commands, and by browsing URLs ```https://github.com/<user>/<repo>/commit/<commitID>.patch``` or ```https://github.com/raw/<user>/<repo>/pull/<PullRequestID>.patch```.

I don't really have advice to give, but perhaps you could use the same system?

As for "what needs to be built"...Well, depend. If you want to contribute to pfSense, you don't need to build anything. You just need to fork the pfSense repo, make your own commits on a separate branch, then your changes using the patch module, then submit a pull request to the original repo when it will be the right time.

**Comment by Hillsie** [comment]
@Augustin-FL  I find the patch process is quite time consuming for Web changes.  It would mean I need to build an ISO for every review. Thanks I might look at using SAMBA to use to share the Web side of the application.

**Comment by Augustin-FL** [comment]
No, you don't.

You can just create & export the .patch, then apply your changes on an existing ISO (pfSense one or one you created, it doesn't matter), Then un-apply your change, perform some modification on the code, then re-create & export the .patch, apply your changes, etc...

At some point, when your feature will be ready ("eg : Migrate all GUI to a new bootstrap version"), you could commit it.

**Comment by Hillsie** [comment]
@Augustin-FL This is a whole git process I am not familiar with... Linux vs Web :-)
I'm interested in learning more.  
Ok, let me see if I understand.
* Clone the repo(s) onto my host machine
* Create the VM. Pull the git repo from the host into the vm. (Not entirely sure how to pull in a  local host git repo into the local vm) then
* Build the pfsense ISO on my vm as you describe in this git documentation
* Create my changes on the host machine and apply patches in the iso on the vm.
* Use the ISO installation process on an x86 machine or vm

Ok, I probably need to find some doco on this as I am not familiar with the linux patch process.
Any reference material you could point me to?

**Comment by Augustin-FL** [comment]
> @Augustin-FL This is a whole git process I am not familiar with... Linux vs Web :-)

Git processes aren't Linux specific. Git also exists on windows. And also exists for web projects. Proof here with [github.com itself](https://github.com/github/government.github.com).


If you are looking for Git workflows material, i would recommend you https://nvie.com/posts/a-successful-git-branching-model/
If you are however looking for patches material, you can have a look to https://01.org/linuxgraphics/gfx-docs/drm/process/applying-patches.html

Nowadays, the patch mechanism is almost not used anymore (people do use git branches instead. `git checkout someTestBranch` is easier than getting a patch, applying it, etc..).  
pfSense doesn't support this workflow with checkouts (the reason being : pfSense is FreeBSD based, and freeBSD does not support this workflow, because some components need to be compiled). So you'll have to use the patch system.

**Comment by Hillsie** [comment]
Thanks, the third link is what I'm after.  I'm not familiar  with the process of applying a `git` patch to an ISO.  Regards `git`, use it everyday however, not in the FreeBSD patch approach ... and windows ...haven't used windows in years :laughing: 

The challenge I'm researching is how to create an efficient development environment for the `bootstrap` web component.
