### ISSUE TITLE
Hello, 

### ISSUE THREAD

**Issue by aminbaik88** [Augustin-FL/building-pfsense-iso-from-source#36]

**Comment by aminbaik88** [comment]
can i get ur email or Skype pleas ?

**Comment by Augustin-FL** [comment]
hello,

why would you need it? Github issues work well ?

**Comment by aminbaik88** [comment]
i want to help me directly with building custom iso ....

**Comment by Augustin-FL** [comment]
I am not offering private support, sorry

can I close this issue?

**Comment by aminbaik88** [comment]
ok , i will use the issue to ask you. hope that you can support
