### ISSUE TITLE
port build fetch problem

### ISSUE THREAD

**Issue by aminbaik88** [Augustin-FL/building-pfsense-iso-from-source#38]
Hello, 
i get a problem with building some packages that is not on the main freebsd distrepo i found it on http://distfiles.icmpv6.org/distfiles/ how i can link it ?
Thanks.

**Comment by Augustin-FL** [comment]
This is clearly out of scope of this tutorial

I invite you to read the freebsd documentation : https://docs.freebsd.org/doc/5.2-RELEASE/usr/share/doc/en_US.ISO8859-1/books/porters-handbook/makefile-distfiles.html

Here you will find a lot of explanations about what are distfiles and how to use them
