### ISSUE TITLE
./build.sh --skip-final-rsync iso Error

### ISSUE THREAD

**Issue by sreekupm** [Augustin-FL/building-pfsense-iso-from-source#4]
Dear Augustin,

While running "./build.sh --skip-final-rsync iso" getting error, please help to solve the issue 

>>> Installing kernel MyFirewall completed on Fri Oct 25 10:54:01 IST 2019
--------------------------------------------------------------
====>> Compressing kernel
>>> Cloning everything to /root/pfsense/tmp/stage-dir staging area...mv: rename /root/pfsense/tmp/stage-dir/usr/local/sbin/pfSense-upgrade to /root/pfsense/tmp/stage-dir/usr/local/sbin/MyFirewall-upgrade: No such file or directory
sed: /root/pfsense/tools/templates/pkg_repos/MyFirewall-repo-devel.abi: No such file or directory
sed: /root/pfsense/tools/templates/pkg_repos/MyFirewall-repo-devel.altabi: No such file or directory
====>> Copying metadata for package rc
====>> Creating core package rc
pkg: Unable to access file /root/pfsense/tmp/stage-dir/share/MyFirewall/fix_for_SA-19-10.ufs:No such file or directory
====>> ERROR: Execution of 'pkg create -o /root/pfsense/tmp/MyFirewall_master_amd64-core/.real_20191025-1005/All -p /tmp/rc.6tjjVCY/rc_plist -r /root/pfsense/tmp/stage-dir -m /tmp/rc.6tjjVCY/rc_metadir' failed (rc = 70)
====>> Removing immutable flags from /tmp/rc.6tjjVCY
====>> Removing recursively /tmp/rc.6tjjVCY

####################################
Something went wrong, check errors!
####################################

NOTE: a lot of times you can run './build.sh --clean-builder' to resolve.

Terminated

**Comment by Augustin-FL** [comment]
quoting from the tutorial :

Change pfSense to libreSense in the file names (e.g., pfSense-repo.abi => libreSense-repo.abi)

https://github.com/Augustin-FL/building-pfsense-iso-from-source/blob/master/README.md#pfsense-gui

**Comment by sreekupm** [comment]
Dear Augustin, 

Getting Error again Please help.

>>> Installing kernel MyFirewall completed on Fri Oct 25 12:34:05 IST 2019
--------------------------------------------------------------
====>> Compressing kernel
>>> Cloning everything to /root/pfsense/tmp/stage-dir staging area...mv: rename /root/pfsense/tmp/stage-dir/usr/local/sbin/pfSense-upgrade to /root/pfsense/tmp/stage-dir/usr/local/sbin/MyFirewall-upgrade: No such file or directory
====>> Copying metadata for package rc
====>> Creating core package rc
pkg: Unable to access file /root/pfsense/tmp/stage-dir/share/MyFirewall/fix_for_SA-19-10.ufs:No such file or directory
====>> ERROR: Execution of 'pkg create -o /root/pfsense/tmp/MyFirewall_master_amd64-core/.real_20191025-1230/All -p /tmp/rc.sJG5WBB/rc_plist -r /root/pfsense/tmp/stage-dir -m /tmp/rc.sJG5WBB/rc_metadir' failed (rc = 70)
====>> Removing immutable flags from /tmp/rc.sJG5WBB
====>> Removing recursively /tmp/rc.sJG5WBB

####################################
Something went wrong, check errors!
####################################

NOTE: a lot of times you can run './build.sh --clean-builder' to resolve.

Terminated

**Comment by Augustin-FL** [comment]
hello,

This is a real issue
It seems like pfSense used a patch following a security advisory from freebsd

see

https://github.com/pfsense/pfsense/commit/7373049764f144b2ea7c891bd60760ab64b41160
