### ISSUE TITLE
export PRODUCT_NAME="fypSense"    failed to execute

### ISSUE THREAD

**Issue by usamasiddique52** [Augustin-FL/building-pfsense-iso-from-source#42]
export PRODUCT_NAME="fypSense"    failed to execute
it gives error export: command not found

**Comment by usamasiddique52** [comment]
I figured it out, use setenv  instead of export

**Comment by usamasiddique52** [comment]
But now got a new error after running this command (export PKG_REPO_SIGNING_COMMAND="/root/sign/sign.sh ${PKG_REPO_SIGN_KEY}")

error message:

PKG_REPO_SIGN_KEY: Undefined variable

**Comment by Augustin-FL** [comment]
This is not supposed to be executed in a live shell.

As explained, you need to create a file called build.conf in the folder of pfSense GUI. Then you need to enter the `export` lines inside.

**Comment by Augustin-FL** [comment]
Can I close this issue?

**Comment by usamasiddique52** [comment]
sure
