### ISSUE TITLE
./build.sh --setup-poudriere error 

### ISSUE THREAD

**Issue by gitmessage** [Augustin-FL/building-pfsense-iso-from-source#44]
follow:building-pfsense-iso-from-source. Error log:

--- _libinstall ---
sh /usr/local/poudriere/jails/libreSense_master_amd64/usr/src/tools/install.sh  -s -o root -g wheel -m 444   -S  libkrb5.so.11 /root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp/usr/lib/
sh /usr/local/poudriere/jails/libreSense_master_amd64/usr/src/tools/install.sh  -o root -g wheel -m 444    libkrb5.so.11.debug /root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp/usr/lib/debug/usr/lib/
sh /usr/local/poudriere/jails/libreSense_master_amd64/usr/src/tools/install.sh -l rs -o root -g wheel -m 755 -S   libkrb5.so.11 /root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp/usr/lib/libkrb5.so
--- secure/lib/libssh__L ---
--- kerberos5/lib/libhdb__L ---
--- secure/lib/libssh__L ---
===> secure/lib/libssh (obj,all,install)
--- kerberos5/lib/libhdb__L ---
===> kerberos5/lib/libhdb (obj,all,install)
--- asn1_Salt.c ---
cp -f asn1_Salt.x asn1_Salt.c
--- asn1_Key.c ---
cp -f asn1_Key.x asn1_Key.c
--- asn1_Event.c ---
cp -f asn1_Event.x asn1_Event.c
--- asn1_HDBFlags.c ---
cp -f asn1_HDBFlags.x asn1_HDBFlags.c
--- asn1_GENERATION.c ---
cp -f asn1_GENERATION.x asn1_GENERATION.c
--- asn1_HDB_Ext_PKINIT_acl.c ---
cp -f asn1_HDB_Ext_PKINIT_acl.x asn1_HDB_Ext_PKINIT_acl.c
--- asn1_HDB_Ext_PKINIT_cert.c ---
cp -f asn1_HDB_Ext_PKINIT_cert.x asn1_HDB_Ext_PKINIT_cert.c
--- secure/lib/libssh__L ---
--- .depend ---
echo libprivatessh.so.5.full: /root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp/usr/lib/libprivateldns.a /root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp/usr/lib/libcrypto.a /root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp/usr/lib/libcrypt.a /root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp/usr/lib/libz.a >> .depend
--- kerberos5/lib/libhdb__L ---
--- asn1_HDB_Ext_PKINIT_hash.c ---
cp -f asn1_HDB_Ext_PKINIT_hash.x asn1_HDB_Ext_PKINIT_hash.c
--- secure/lib/libssh__L ---
--- ssh_api.o ---
cc -target x86_64-unknown-freebsd12.2 --sysroot=/root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp -B/root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp/usr/bin  -O2 -pipe -fno-common   -DHAVE_LDNS=1 -I/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/contrib/ldns -I/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/crypto/openssh -include ssh_namespace.h -include krb5_config.h -g -MD  -MF.depend.ssh_api.o -MTssh_api.o -std=gnu99 -Wno-format-zero-length -fstack-protector-strong -Wno-pointer-sign -Wno-empty-body -Wno-string-plus-int -Wno-unused-const-variable -Wno-tautological-compare -Wno-unused-value -Wno-parentheses-equality -Wno-unused-function -Wno-enum-conversion -Wno-unused-local-typedef -Wno-address-of-packed-member -Wno-switch -Wno-switch-enum -Wno-knr-promoted-parameter -Wno-parentheses  -Qunused-arguments  -c /usr/local/poudriere/jails/libreSense_master_amd64/usr/src/crypto/openssh/ssh_api.c -o ssh_api.o
--- kerberos5/lib/libhdb__L ---
--- asn1_HDB_Ext_Constrained_delegation_acl.c ---
cp -f asn1_HDB_Ext_Constrained_delegation_acl.x asn1_HDB_Ext_Constrained_delegation_acl.c
--- asn1_HDB_Ext_Lan_Manager_OWF.c ---
cp -f asn1_HDB_Ext_Lan_Manager_OWF.x asn1_HDB_Ext_Lan_Manager_OWF.c
--- asn1_HDB_Ext_Password.c ---
cp -f asn1_HDB_Ext_Password.x asn1_HDB_Ext_Password.c
--- asn1_HDB_Ext_Aliases.c ---
--- secure/lib/libssh__L ---
In file included from /usr/local/poudriere/jails/libreSense_master_amd64/usr/src/crypto/openssh/ssh_api.c:18:
/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/crypto/openssh/includes.h:19:10: fatal error: 'config.h' file not found
#include "config.h"
         ^~~~~~~~~~
--- kerberos5/lib/libhdb__L ---
cp -f asn1_HDB_Ext_Aliases.x asn1_HDB_Ext_Aliases.c
--- asn1_HDB_extension.c ---
cp -f asn1_HDB_extension.x asn1_HDB_extension.c
--- asn1_HDB_extensions.c ---
cp -f asn1_HDB_extensions.x asn1_HDB_extensions.c
--- asn1_hdb_entry.c ---
cp -f asn1_hdb_entry.x asn1_hdb_entry.c
--- asn1_hdb_entry_alias.c ---
cp -f asn1_hdb_entry_alias.x asn1_hdb_entry_alias.c
--- asn1_hdb_keyset.c ---
cp -f asn1_hdb_keyset.x asn1_hdb_keyset.c
--- hdb_asn1-priv.h ---
cp -f hdb_asn1-priv.hx hdb_asn1-priv.h
--- .depend ---
echo libhdb.so.11.full:  /root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp/usr/lib/libasn1.a /root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp/usr/lib/libcom_err.a /root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp/usr/lib/libkrb5.a /root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp/usr/lib/libroken.a /root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp/usr/lib/libprivatesqlite3.a >> .depend
--- common.o ---
cc -target x86_64-unknown-freebsd12.2 --sysroot=/root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp -B/root/pfsense/tmp/obj/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/amd64.amd64/tmp/usr/bin  -O2 -pipe -fno-common -I/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/crypto/heimdal/lib/hdb -I/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/crypto/heimdal/lib/asn1  -I/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/crypto/heimdal/lib/roken -I/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/contrib/sqlite3/  -I/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/crypto/heimdal/lib/krb5  -I/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/contrib/com_err  -I.  -DHDB_DB_DIR="\"/var/heimdal\""   -DHAVE_CONFIG_H -I/usr/local/poudriere/jails/libreSense_master_amd64/usr/src/kerberos5/include -g -MD  -MF.depend.common.o -MTcommon.o -std=gnu99 -Wno-format-zero-length -fstack-protector-strong -Wno-error=deprecated-declarations -Wsystem-headers -Werror -Wno-pointer-sign -Wno-error=absolute-value -Wno-empty-body -Wno-string-plus-int -Wno-unused-const-variable -Wno-tautological-compare -Wno-unused-value -Wno-parentheses-equality -Wno-unused-function -Wno-enum-conversion -Wno-unused-local-typedef -Wno-address-of-packed-member -Wno-switch -Wno-switch-enum -Wno-knr-promoted-parameter -Wno-parentheses  -Qunused-arguments  -c /usr/local/poudriere/jails/libreSense_master_amd64/usr/src/crypto/heimdal/lib/hdb/common.c -o common.o
--- secure/lib/libssh__L ---
1 error generated.
*** [ssh_api.o] Error code 1

make[4]: stopped in /usr/local/poudriere/jails/libreSense_master_amd64/usr/src/secure/lib/libssh
1 error

make[4]: stopped in /usr/local/poudriere/jails/libreSense_master_amd64/usr/src/secure/lib/libssh
--- kerberos5/lib/libhdb__L ---
[00:27:15] Error: Failed to 'make buildworld'
[00:27:15] Error while creating jail, cleaning up.
[00:27:15] Removing libreSense_master_amd64 jail... done
[00:27:16] Cleaning libreSense_master_amd64 data... done

Thanks!

**Comment by gitmessage** [comment]
my private gitlab lost file: config.h
./build.sh --setup-poudriere  is finish.
I am dong next setp:./build.sh --update-pkg-repo
Thanks!

**Comment by gitmessage** [comment]
close this issues

**Comment by abmwine** [comment]
> my private gitlab lost file: config.h ./build.sh --setup-poudriere is finish. I am dong next setp:./build.sh --update-pkg-repo Thanks!

I am facing the same error, please elaborate where this file should be
