### ISSUE TITLE
"./build.sh --skip-final-rsync iso " error

### ISSUE THREAD

**Issue by gitmessage** [Augustin-FL/building-pfsense-iso-from-source#48]
--------------------------------------------------------------
>>> Installing kernel GFireWall completed on Mon Jul 19 00:22:43 CST 2021
--------------------------------------------------------------
====>> Compressing kernel
>>> Cloning everything to /root/pfsense/tmp/stage-dir staging area...====>> Copying metadata for package rc
====>> Creating core package rc
pkg: cannot load keyword from /usr/ports/Keywords/shell.ucl: No such file or directory
pkg: unknown keyword shell: @shell
====>> ERROR: Execution of 'pkg create -o /root/pfsense/tmp/GFireWall_v2_5_0_amd64-core/.real_20210719-0016/All -p /tmp/rc.z1poVzm/rc_plist -r /root/pfsense/tmp/stage-dir -m /tmp/rc.z1poVzm/rc_metadir' failed (rc = 1)
====>> Removing immutable flags from /tmp/rc.z1poVzm
====>> Removing recursively /tmp/rc.z1poVzm

####################################
Something went wrong, check errors!
####################################

NOTE: a lot of times you can run './build.sh --clean-builder' to resolve.

Terminated

Thinks!

**Comment by gitmessage** [comment]
cd /usr/ports/
ls
only:distfiles

**Comment by Augustin-FL** [comment]
Hi,

What's the branch of the FreeBSD ports, FreeBSD jail, & pfSense GUI that you used during your build? 

Also, did you execute ```portsnap fetch extract``` in your VM?

**Comment by gitmessage** [comment]
I forgot run "portsnap fetch extract"
Great!
Thanks
