### ISSUE TITLE
 ./build.sh --skip-final-rsync iso error pkg: Unable to access file /root/pfsense/tmp/stage-dir/share/MyFirewall/fix_for_SA-19-10.ufs:No such file or directory

### ISSUE THREAD

**Issue by sreekupm** [Augustin-FL/building-pfsense-iso-from-source#5]
Dear Augustin,

Getting Error again Please help.

Installing kernel MyFirewall completed on Fri Oct 25 12:34:05 IST 2019

====>> Compressing kernel

Cloning everything to /root/pfsense/tmp/stage-dir staging area...mv: rename /root/pfsense/tmp/stage-dir/usr/local/sbin/pfSense-upgrade to /root/pfsense/tmp/stage-dir/usr/local/sbin/MyFirewall-upgrade: No such file or directory
====>> Copying metadata for package rc
====>> Creating core package rc
pkg: Unable to access file /root/pfsense/tmp/stage-dir/share/MyFirewall/fix_for_SA-19-10.ufs:No such file or directory
====>> ERROR: Execution of 'pkg create -o /root/pfsense/tmp/MyFirewall_master_amd64-core/.real_20191025-1230/All -p /tmp/rc.sJG5WBB/rc_plist -r /root/pfsense/tmp/stage-dir -m /tmp/rc.sJG5WBB/rc_metadir' failed (rc = 70)
====>> Removing immutable flags from /tmp/rc.sJG5WBB
====>> Removing recursively /tmp/rc.sJG5WBB

####################################
Something went wrong, check errors!
####################################

NOTE: a lot of times you can run './build.sh --clean-builder' to resolve.

Terminated

**Comment by Augustin-FL** [comment]
hello,

This is following recent (..yesterday) updates on pfSense.

It seems like pfSense is trying to apply a patch, following a security advisory from freebsd. This patch wasn't applied correctly, causing all builds (even netgate one) to fail. As far as I understand, Netgat is going to fix the issue

see

https://github.com/pfsense/pfsense/commit/7373049764f144b2ea7c891bd60760ab64b41160 , https://github.com/pfsense/pfsense/commit/14d49fba46389e3f90d26c6316044dfb52f98fc9
and 
https://www.freebsd.org/security/advisories/FreeBSD-SA-19:10.ufs.asc

**Comment by Augustin-FL** [comment]
I updated the guidelines based on your feedback.

Thanks ! :)
