### ISSUE TITLE
./build.sh --update-pkg-repo error 

### ISSUE THREAD

**Issue by hanqianxun** [Augustin-FL/building-pfsense-iso-from-source#51]
I'm new to FreeBSD. I'm compiling pfsense.
When the following command is executed,i get an error:

pkg repo /usr/local/poudriere/data/packages/jzsense_v2_5_0_amd64-jzSense_v2_5_0/.real_ 1640129320/
pkg: no package files have been found
cannot create repository catalog.

pkg -v
1.17.5

ls /usr/local/poudriere/data/packages/jzsense_v2_5_0_amd64-jzSense_v2_5_0/.real_ 1640129320/
.buildname All logs meta.txz packagesite.yaml
.jailversion Latest meta.conf packagesite.txz

When i install pkg 1.16.3 version this commond execute well.But i don't want to do this as this 1.16.3 version is different with pfsense pkg 1.17.5 version.

Can anyone help me ,thank you.

**Comment by lpc-v** [comment]
I met this problem too ,
can you tell me how to install pkg 1.16.3 ? I'm new to FreeBSD too.

**Comment by lpc-v** [comment]
Or,  have you find the solution to this problem, could you share with me? I'm waiting for your reply.
