### ISSUE TITLE
Jail is newer than host. (Jail: 1202504, Host: 1202000)

### ISSUE THREAD

**Issue by lpc-v** [Augustin-FL/building-pfsense-iso-from-source#52]
when building the port, there are 5 port failed because 

!!! Jail is newer than host. (Jail: 1202504, Host: 1202000) !!!
!!! This is not supported. !!!
!!! Host kernel must be same or newer than jail. !!!
!!! Expect build failures. !!!

I use **uname -K** to check my freeBSD kernel version， and it is excatly 1202000.
How to update my kernel to match the Jail created?

**Comment by Augustin-FL** [comment]
This is generally okay, it's not a big issue in itself.

You can optionally compile freebsd itself in order to have a more recent host version. But i personally think it's overkill

Unless you are facing issues later in the build, you can safely ignore this warning.

**Comment by Augustin-FL** [comment]
I will close this issue, feel free to re-open it if you find that the jail version mismatch indeed impact the build.
