### ISSUE TITLE
Signing repository failed...

### ISSUE THREAD

**Issue by lpc-v** [Augustin-FL/building-pfsense-iso-from-source#53]
when building the ports, all the ports succeeded, but at the end there is an error:

> root@:~/pfsense # cat logs/poudriere.log 
> >>> Signing repository... pkg: No package files have been found
> Cannot create repository catalogue
> Failed!

what's the reason??? If I ignore this error and then build iso, it will fail

> Installing built ports (packages) in chroot (/root/pfsense/tmp/stage-dir)... Failed!

**Comment by Augustin-FL** [comment]
Hi,

This error indicate that ``/usr/local/poudriere/data/packages/libreSense_master_amd64-libreSense_devel/meta.conf`` is missing. This file is generated by poudriere at the end of the build (when *ALL* ports have been successfully built).

Could you please double check if poudriere ran successfully? 
If so, there should be some .txz & .pkg (meta.txz, packagesite.txz, etc...) in ``/usr/local/poudriere/data/packages/libreSense_master_amd64-libreSense_devel/``. Are they here?

if they are not here, then you can debug build.sh (using `set -x`) to understand what's the issue. The line performing the signing command is [here](https://github.com/pfsense/pfsense/blob/master/tools/builder_common.sh#L1369-L1371).

**Comment by Augustin-FL** [comment]
Hi,

Can I close this issue?
