### ISSUE TITLE
Building pfSense iso for RELENG_2_7_1 Release

### ISSUE THREAD

**Issue by MehrozMustafa** [Augustin-FL/building-pfsense-iso-from-source#58]
While building pfsense 2_5_0 from source, I was facing these issues
```
Bootstrapping pkg from pkg+http://fe80::a00:27ff:fe85:ea35%em0/packages/libreSense_v2_5_1_amd64-libreSense_v2_5_1, please wait...
pkg: fetchParseURL('http://fe80::a00:27ff:fe85:ea35%em0/packages/libreSense_v2_5_1_amd64-libreSense_v2_5_1/Latest/pkg.txz'): No such file or directory
pkg: Error fetching http://fe80::a00:27ff:fe85:ea35%em0/packages/libreSense_v2_5_1_amd64-libreSense_v2_5_1/Latest/pkg.txz: Invalid server port
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.
Bootstrapping pkg from pkg+http://fe80::a00:27ff:fe85:ea35%em0/packages/libreSense_v2_5_1_amd64-libreSense_v2_5_1, please wait...
pkg: fetchParseURL('http://fe80::a00:27ff:fe85:ea35%em0/packages/libreSense_v2_5_1_amd64-libreSense_v2_5_1/Latest/pkg.txz'): No such file or directory
pkg: Error fetching http://fe80::a00:27ff:fe85:ea35%em0/packages/libreSense_v2_5_1_amd64-libreSense_v2_5_1/Latest/pkg.txz: Invalid server port
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.
Bootstrapping pkg from pkg+http://fe80::a00:27ff:fe85:ea35%em0/packages/libreSense_v2_5_1_amd64-libreSense_v2_5_1, please wait...
pkg: fetchParseURL('http://fe80::a00:27ff:fe85:ea35%em0/packages/libreSense_v2_5_1_amd64-libreSense_v2_5_1/Latest/pkg.txz'): No such file or directory
pkg: Error fetching http://fe80::a00:27ff:fe85:ea35%em0/packages/libreSense_v2_5_1_amd64-libreSense_v2_5_1/Latest/pkg.txz: Invalid server port
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.
```

**Comment by rifkadroid** [comment]
please update, how to create iso from source for releng 2_7_1

**Comment by MehrozMustafa** [comment]
> please update, how to create iso from source for releng 2_7_1

What I found so far,
Follow the first few steps of his link related to renaming some files and changing some variable values which holds the name for pfSense to libreSense or any other name you desire, then simply start the build process,

There were alot of errros I've faced, which one can resolve one by one by adding `set -x` in the build.sh files
As for the process of solving each error, I'm still working on creating my own guide for it.

**Comment by timruangserver** [comment]
I have created an ISO, at the testing stage, on the website display an error appears requiring vendor autoload. I checked the vendor folder at /product name/includes/vendor, it doesn't exist. Can you help me bro ?

**Comment by kontrol-br** [comment]
> I have created an ISO, at the testing stage, on the website display an error appears requiring vendor autoload. I checked the vendor folder at /product name/includes/vendor, it doesn't exist. Can you help me bro ?

The "product_name" is a variable. It must match your firewall's name. (You can't use pfsense) - read the above message from Mehroz. He is explaining the same thing. You have to rename some folders and files to match your firewall's name. (be aware that everything is case sensitive)
