### ISSUE TITLE
libreSense-repo-2.4.4_5 depends on file: /usr/local/sbin/libreSense-upgrade - not found

### ISSUE THREAD

**Issue by tajummal-lab** [Augustin-FL/building-pfsense-iso-from-source#6]
i need yours help kidly help me
 libreSense-repo-2.4.4_5 depends on file: /usr/local/sbin/libreSense-upgrade - not found
===>   Installing existing package /packages/All/pfSense-upgrade-0.62.txz
[libreSense_v2_4_4_amd64-libreSense_v2_4_4-job-02] Installing pfSense-upgrade-0.62...
[libreSense_v2_4_4_amd64-libreSense_v2_4_4-job-02] Extracting pfSense-upgrade-0.62: ..... done
===>   libreSense-repo-2.4.4_5 depends on file: /usr/local/sbin/libreSense-upgrade - not found
*** Error code 1

Stop.
make: stopped in /usr/ports/sysutils/libreSense-repo
=>> Cleaning up wrkdir
===>  Cleaning for libreSense-repo-2.4.4_5
build of sysutils/libreSense-repo | libreSense-repo-2.4.4_5 ended at Sat Oct 26 04:52:43 UTC 2019
build time: 00:00:02
!!! build failure encountered !!!

**Comment by Augustin-FL** [comment]
could you first confirm that you have read and appplied https://github.com/Augustin-FL/building-pfsense-iso-from-source#freebsd-ports ?

**Comment by tajummal-lab** [comment]
Sir
I repeat these steps multiple times now I'm again compiling

**Comment by Augustin-FL** [comment]
it seems like you forgot to execute `Also rename the folder /sysutils/pfSense-upgrade/ to /sysutils/libreSense-upgrade/`

**Comment by tajummal-lab** [comment]
Kindly provide me yours email address so that i can easily contact you
regarding this issue

**Comment by tajummal-lab** [comment]
I started compilation again
With Pfsense ( master )
And pfsense (devel)
At that time i got 3 build failed in packages
devel/boost-libs| boost-libs-1.71.0
Lang/rust | rust-1.38.0
Lang/go | go-1.13.1,1

**Comment by tajummal-lab** [comment]
Now just one build error left
Rust 1.38 build failed.
What is the rust version in your repository.
And how can i chng this in pfsense freeBSD ports or manually using wget??

**Comment by Augustin-FL** [comment]
please see #1 then
your problem is likely related to the same cause

**Comment by tejaskarelia17** [comment]
Hi,
I am trying to build with the following configuration:
FreeBSD-src - RELENG_2_5
FreeBSD-ports - devel
pfSense - master

I am getting the following error: 

[01:00:38] Failed ports: sysutils/libreSense-upgrade:stage
[01:00:38] Skipped ports: security/libreSense sysutils/libreSense-repo
[libreSense_master_amd64-libreSense_devel] [2019-11-14_16h53m37s] [pkgrepo:] Queued: 501 Built: 498 Failed: 1   Skipped: 2   Ignored: 0   Tobuild: 0    Time: 01:00:36

Please find attached the log file.
`=>> Building sysutils/libreSense-upgrade
build started at Thu Nov 14 17:11:11 PST 2019
port directory: /usr/ports/sysutils/libreSense-upgrade
package name: libreSense-upgrade-0.69
building for: FreeBSD libreSense_master_amd64-libreSense_devel-job-03 12.0-RELEASE-p10 FreeBSD 12.0-RELEASE-p10 1200086 amd64
maintained by: coreteam@pfsense.org
Makefile ident: 
Poudriere version: 3.3.99.20190828
Host OSVERSION: 1200086
Jail OSVERSION: 1200086
Job Id: 03

---Begin Environment---
SHELL=/bin/csh
OSVERSION=1200086
UNAME_v=FreeBSD 12.0-RELEASE-p10 1200086
UNAME_r=12.0-RELEASE-p10
BLOCKSIZE=K
MAIL=/var/mail/root
STATUS=1
HOME=/root
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
LOCALBASE=/usr/local
USER=root
LIBEXECPREFIX=/usr/local/libexec/poudriere
POUDRIERE_VERSION=3.3.99.20190828
MASTERMNT=/usr/local/poudriere/data/.m/libreSense_master_amd64-libreSense_devel/ref
POUDRIERE_BUILD_TYPE=bulk
PACKAGE_BUILDING=yes
SAVED_TERM=screen
GID=0
UID=0
PWD=/usr/local/poudriere/data/.m/libreSense_master_amd64-libreSense_devel/ref/.p/pool
P_PORTS_FEATURES=FLAVORS SELECTED_OPTIONS
MASTERNAME=libreSense_master_amd64-libreSense_devel
SCRIPTPREFIX=/usr/local/share/poudriere
OLDPWD=/usr/local/poudriere/data/.m/libreSense_master_amd64-libreSense_devel/ref/.p
SCRIPTPATH=/usr/local/share/poudriere/bulk.sh
POUDRIEREPATH=/usr/local/bin/poudriere
---End Environment---

---Begin Poudriere Port Flags/Env---
PORT_FLAGS=
PKGENV=
FLAVOR=
DEPENDS_ARGS=
MAKE_ARGS=
---End Poudriere Port Flags/Env---

---Begin OPTIONS List---
---End OPTIONS List---

--MAINTAINER--
coreteam@pfsense.org
--End MAINTAINER--

--CONFIGURE_ARGS--

--End CONFIGURE_ARGS--

--CONFIGURE_ENV--
XDG_DATA_HOME=/wrkdirs/usr/ports/sysutils/libreSense-upgrade/work  XDG_CONFIG_HOME=/wrkdirs/usr/ports/sysutils/libreSense-upgrade/work  HOME=/wrkdirs/usr/ports/sysutils/libreSense-upgrade/work TMPDIR="/tmp" PATH=/wrkdirs/usr/ports/sysutils/libreSense-upgrade/work/.bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin SHELL=/bin/sh CONFIG_SHELL=/bin/sh
--End CONFIGURE_ENV--

--MAKE_ENV--
XDG_DATA_HOME=/wrkdirs/usr/ports/sysutils/libreSense-upgrade/work  XDG_CONFIG_HOME=/wrkdirs/usr/ports/sysutils/libreSense-upgrade/work  HOME=/wrkdirs/usr/ports/sysutils/libreSense-upgrade/work TMPDIR="/tmp" PATH=/wrkdirs/usr/ports/sysutils/libreSense-upgrade/work/.bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS=""  LDFLAGS=" -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444"
--End MAKE_ENV--

--PLIST_SUB--
OSREL=12.0 PREFIX=%D LOCALBASE=/usr/local  RESETPREFIX=/usr/local LIB32DIR=lib DOCSDIR="share/doc/libreSense-upgrade"  EXAMPLESDIR="share/examples/libreSense-upgrade"  DATADIR="share/libreSense-upgrade"  WWWDIR="www/libreSense-upgrade"  ETCDIR="etc/libreSense-upgrade"
--End PLIST_SUB--

--SUB_LIST--
PREFIX=/usr/local LOCALBASE=/usr/local  DATADIR=/usr/local/share/libreSense-upgrade DOCSDIR=/usr/local/share/doc/libreSense-upgrade EXAMPLESDIR=/usr/local/share/examples/libreSense-upgrade  WWWDIR=/usr/local/www/libreSense-upgrade ETCDIR=/usr/local/etc/libreSense-upgrade
--End SUB_LIST--

---Begin make.conf---
USE_PACKAGE_DEPENDS=yes
BATCH=yes
WRKDIRPREFIX=/wrkdirs
PORTSDIR=/usr/ports
PACKAGES=/packages
DISTDIR=/distfiles
FORCE_PACKAGE=yes
PACKAGE_BUILDING=yes
PACKAGE_BUILDING_FLAVORS=yes
#### /usr/local/etc/poudriere.d/libreSense_devel-make.conf ####
# Define pfSense repos
PFSENSE_REPOS=	pfSense-repo pfSense-repo-devel

# Generic options
OPTIONS_UNSET_FORCE=	X11 DOCS EXAMPLES MAN INFO MANPAGES

# Individual ports options
.if ${.CURDIR:N*net/quagga*}=="" || ${.CURDIR:N*net/frr*}==""
CUR_ARCH!=	/usr/bin/uname -p
. if ${CUR_ARCH} == "armv7"
WITH_DEBUG=yes
. endif
.endif

.if ${.CURDIR:N*net/rsync*}==""
CFLAGS+=	-static
.endif

.if ${.CURDIR:N*security/openiked*}==""
CONFIGURE_ARGS=	--without-openssl-header-check
.endif

DEFAULT_VERSIONS=	php=73 ssl=base python=3.6
PHP_FD_SETSIZE=		3172

. if ${.CURDIR:N*sysutils/check_reload_status*}==""
WITH_DEBUG=	yes
. endif

# Options for packages

# databases
databases_rrdtool12_UNSET_FORCE=	PERL

databases_rrdtool_UNSET_FORCE=	PYTHON_MODULE RUBY_MODULE PERL_MODULE DEJAVU GRAPH

# devel
devel_apr1_SET_FORCE=IPV6 SQLITE SSL THREADS
devel_apr1_UNSET_FORCE=BDB MYSQL NSS PGSQL

devel_git_UNSET_FORCE=CVS GITWEB GUI HTMLDOCS P4 SVN CONTRIB PERL ETCSHELLS

# dns
dns_unbound_SET_FORCE=	LIBEVENT PYTHON

dns_bind-pfsense_SET_FORCE=DLZ_FILESYSTEM FILTER_AAAA IPV6 LINKS RRL SIGCHASE SSL THREADS GSSAPI_NONE
dns_bind-pfsense_UNSET_FORCE=FIXED_RRSET IDN LARGE_FILE LMDB

dns_bind99_SET_FORCE=DLZ_FILESYSTEM FILTER_AAAA IPV6 LINKS RRL SIGCHASE SSL THREADS GSSAPI_NONE
dns_bind99_UNSET_FORCE=FIXED_RRSET IDN LARGE_FILE

dns_bind910_SET_FORCE=DLZ_FILESYSTEM FILTER_AAAA IPV6 LINKS RRL SIGCHASE SSL THREADS GSSAPI_NONE
dns_bind910_UNSET_FORCE=FIXED_RRSET IDN LARGE_FILE

dns_bind911_SET_FORCE=DLZ_FILESYSTEM FILTER_AAAA IPV6 LINKS RRL SIGCHASE SSL THREADS GSSAPI_NONE
dns_bind911_UNSET_FORCE=FIXED_RRSET IDN LARGE_FILE LMDB

dns_bind912_SET_FORCE=DLZ_FILESYSTEM FILTER_AAAA IPV6 LINKS RRL SIGCHASE SSL THREADS GSSAPI_NONE
dns_bind912_UNSET_FORCE=FIXED_RRSET IDN LARGE_FILE LMDB

# emulators
emulators_qemu_UNSET_FORCE=	SDL

# graphics
graphics_cairo_UNSET_FORCE=X11 XCB OPENGL

graphics_gd_SET_FORCE=ICONV
graphics_gd_UNSET_FORCE=FONTCONFIG XPM

graphics_graphviz_SET_FORCE=ICONV NLS
graphics_graphviz_UNSET_FORCE=DIGCOLA IPSEPCOLA PANGOCAIRO XPM

# lang
lang_gcc_UNSET_FORCE=JAVA

# mail
mail_pear-Mail_SET_FORCE=	PEAR_NET_SMTP

# net
net_avahi_UNSET_FORCE=GTK

net_freeradius2_SET_FORCE=KERBEROS LDAP MYSQL PERL PGSQL PYTHON SSL_PORT
net_freeradius3_SET_FORCE=HEIMDAL LDAP MYSQL PERL PGSQL PYTHON SQLITE3

net_haproxy17_SET_FORCE=OPENSSL SPCRE LUA
net_haproxy17_UNSET_FORCE=DPCRE

net_haproxy18_SET_FORCE=OPENSSL SPCRE LUA
net_haproxy18_UNSET_FORCE=DPCRE

net_haproxy_SET_FORCE=OPENSSL SPCRE LUA
net_haproxy_UNSET_FORCE=DPCRE

net_haproxy-devel_SET_FORCE=OPENSSL SPCRE LUA
net_haproxy-devel_UNSET_FORCE=DPCRE

net_libpcap_SET_FORCE=IPV6
net_libpcap_UNSET_FORCE=DAG

net_libzmq4_UNSET_FORCE=PGM

net_miniupnpd_SET_FORCE=	PF_FILTER_RULES IPV6

net_mtr_UNSET_FORCE=X11

net_nss_ldap_UNSET_FORCE=SASL KERBEROS

net_ntp_UNSET_FORCE=	PERL_UTILS

net_relayd_SET_FORCE=	LIBEVENT_STATIC

# net-mgmt
net-mgmt_net-snmp_SET_FORCE=IPV6 MFD_REWRITES TLS
net-mgmt_net-snmp_UNSET_FORCE=AX_DISABLE_TRAP AX_SOCKONLY DOCS DUMMY JAIL MYSQL PYTHON SMUX TKMIB UNPRIVILEGED

net-mgmt_zabbix22-agent_SET_FORCE=IPV6

net-mgmt_zabbix22-proxy_SET_FORCE=IPMI IPV6 LIBXML2 SQLITE SSH
net-mgmt_zabbix22-proxy_UNSET_FORCE=JABBER MYSQL

net-mgmt_zabbix3-agent_SET_FORCE=IPV6

net-mgmt_zabbix3-proxy_SET_FORCE=IPMI IPV6 LIBXML2 SQLITE SSH
net-mgmt_zabbix3-proxy_UNSET_FORCE=MYSQL

net-mgmt_zabbix4-agent_SET_FORCE=IPV6

net-mgmt_zabbix4-proxy_SET_FORCE=IPMI IPV6 LIBXML2 SQLITE SSH
net-mgmt_zabbix4-proxy_UNSET_FORCE=MYSQL

net-mgmt_zabbix42-agent_SET_FORCE=IPV6

net-mgmt_zabbix42-proxy_SET_FORCE=IPMI IPV6 LIBXML2 SQLITE SSH
net-mgmt_zabbix42-proxy_UNSET_FORCE=MYSQL

net-mgmt_zabbix44-agent_SET_FORCE=IPV6

net-mgmt_zabbix44-proxy_SET_FORCE=IPMI IPV6 LIBXML2 SQLITE SSH
net-mgmt_zabbix44-proxy_UNSET_FORCE=MYSQL

# security
security_barnyard2_SET_FORCE=BRO GRE IPV6 MPLS MYSQL PORT_PCAP
security_barnyard2_UNSET_FORCE=ODBC PGSQL PRELUDE

security_ca_root_nss_SET_FORCE=	ETCSYMLINK

security_openvpn_UNSET_FORCE=	EASYRSA

shells_scponly_SET_FORCE=CHROOT SCP WILDCARDS WINSCP
shells_scponly_UNSET_FORCE=DEFAULT_CHDIR DOCS GFTP RSYNC SVN SVNSERVE UNISON

security_sudo_SET_FORCE=LDAP

security_snort_SET_FORCE=APPID BARNYARD GRE IPV6 NORMALIZER PERFPROFILE SOURCEFIRE
security_snort_UNSET_FORCE=FILEINSPECT HA PULLEDPORK

security_snortsam_UNSET_FORCE=	IPFW

.if ${.CURDIR:N*security/snort3*}==""
CUR_ARCH!=  /usr/bin/uname -p
.if ${CUR_ARCH} == "armv7" || ${CUR_ARCH} == "aarch64"
security_snort3_SET_FORCE=LARGEPCAP STATICDAQ
security_snort3_UNSET_FORCE=HYPERSCAN TSC
else
security_snort3_SET_FORCE=LARGEPCAP STATICDAQ HYPERSCAN
.endif
.endif

security_strongswan_SET_FORCE=	CURL EAPDYNAMIC EAPRADIUS EAPSIMFILE \
			IKEv1 UNBOUND XAUTH IPSECKEY PKCS11 PKI UNITY VICI VSTR SWANCTL
security_strongswan_UNSET_FORCE=	EAPAKA3GPP2 BUILTIN LIBC SMP

security_suricata_SET_FORCE=GEOIP HTP_PORT IPFW JSON LUAJIT NSS PORTS_PCAP NETMAP HYPERSCAN REDIS
.if ${.CURDIR:N*security/suricata*}==""
CUR_ARCH!=	/usr/bin/uname -p
.if ${CUR_ARCH} == "armv7" || ${CUR_ARCH} == "aarch64"
security_suricata_UNSET_FORCE=LUA PRELUDE SC TESTS RUST
.else
security_suricata_UNSET_FORCE=LUA PRELUDE SC TESTS
.endif
.endif

security_xinetd_UNSET_FORCE=	XCONV

# sysutils
sysutils_apcupsd_SET_FORCE=APCDUMB_DRV APCSMART_DRV PCNET_DRV SNMP_DRV TCP_WRAPPERS USB
sysutils_apcupsd_UNSET_FORCE=CGI CLIENT_ONLY GAPCMON SNMP_DRV_OLD TEST_DRV

sysutils_flashrom_UNSET_FORCE=	FTDI BUSPIRATE

sysutils_pftop_SET_FORCE=ALTQ

sysutils_syslog-ng_SET_FORCE=	SYS_SSL
sysutils_syslog-ng_UNSET_FORCE=	PORTS_SSL

# www
www_c-icap_SET_FORCE=LARGE_FILES
www_c-icap_UNSET_FORCE=IPV6

www_lightsquid_SET_FORCE=GD

www_lighttpd_SET_FORCE=	NODELAY

www_nginx_SET_FORCE=	LUA

www_squid_SET_FORCE=ARP_ACL AUTH_LDAP AUTH_NIS AUTH_SASL CACHE_DIGESTS DELAY_POOLS FOLLOW_XFF FS_AUFS FS_DISKD GSSAPI_MIT HTCP ICAP ICMP IDENT IPV6 KQUEUE LARGEFILE LAX_HTTP SNMP SSL SSL_CRTD TP_PF WCCP WCCPV2
www_squid_UNSET_FORCE=AUTH_SMB AUTH_SQL DEBUG DNS_HELPER ECAP ESI FS_ROCK GSSAPI_NONE GSSAPI_BASE GSSAPI_HEIMDAL STACKTRACES TP_IPF TP_IPFW VIA_DB

www_squid3_SET_FORCE=ARP_ACL AUTH_LDAP AUTH_NIS AUTH_SASL CACHE_DIGESTS DELAY_POOLS FOLLOW_XFF FS_AUFS FS_DISKD GSSAPI_MIT HTCP ICAP ICMP IDENT IPV6 KQUEUE LARGEFILE LAX_HTTP SNMP SSL SSL_CRTD TP_PF WCCP WCCPV2
www_squid3_UNSET_FORCE=AUTH_SMB AUTH_SQL DEBUG DNS_HELPER ECAP ESI FS_ROCK GSSAPI_NONE GSSAPI_BASE GSSAPI_HEIMDAL STACKTRACES TP_IPF TP_IPFW VIA_DB

www_squidguard_SET_FORCE=DNS_BL LDAP STRIP_NTDOMAIN
www_squidguard_UNSET_FORCE=QUOTE_STRING

net_frr7_SET_FORCE=MULTIPATH

PKG_REPO_BRANCH_DEVEL=master
PKG_REPO_BRANCH_RELEASE=v2_4_4
PKG_REPO_SERVER_DEVEL=pkg+http://10.4.1.80/packages
PKG_REPO_SERVER_RELEASE=pkg+http://10.4.1.80/packages
POUDRIERE_PORTS_NAME=libreSense_devel
PFSENSE_DEFAULT_REPO=libreSense-repo-devel
PRODUCT_NAME=libreSense
REPO_BRANCH_PREFIX=
#### /usr/ports/Mk/Scripts/ports_env.sh ####
_CCVERSION_921dbbb2=FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1) Target: x86_64-unknown-freebsd12.0 Thread model: posix InstalledDir: /usr/bin
_ALTCCVERSION_921dbbb2=none
_CXXINTERNAL_acaad9ca=FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1) Target: x86_64-unknown-freebsd12.0 Thread model: posix InstalledDir: /usr/bin "/usr/bin/ld" "--eh-frame-hdr" "-dynamic-linker" "/libexec/ld-elf.so.1" "--hash-style=both" "--enable-new-dtags" "-o" "a.out" "/usr/lib/crt1.o" "/usr/lib/crti.o" "/usr/lib/crtbegin.o" "-L/usr/lib" "/dev/null" "-lc++" "-lm" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "-lc" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "/usr/lib/crtend.o" "/usr/lib/crtn.o"
CC_OUTPUT_921dbbb2_58173849=yes
CC_OUTPUT_921dbbb2_9bdba57c=yes
CC_OUTPUT_921dbbb2_6a4fe7f5=yes
CC_OUTPUT_921dbbb2_6bcac02b=yes
CC_OUTPUT_921dbbb2_67d20829=yes
CC_OUTPUT_921dbbb2_bfa62e83=yes
CC_OUTPUT_921dbbb2_f0b4d593=yes
CC_OUTPUT_921dbbb2_308abb44=yes
CC_OUTPUT_921dbbb2_f00456e5=yes
CC_OUTPUT_921dbbb2_65ad290d=yes
CC_OUTPUT_921dbbb2_f2776b26=yes
CC_OUTPUT_921dbbb2_b2657cc3=yes
CC_OUTPUT_921dbbb2_380987f7=yes
CC_OUTPUT_921dbbb2_160933ec=yes
CC_OUTPUT_921dbbb2_fb62803b=yes
_OBJC_CCVERSION_921dbbb2=FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1) Target: x86_64-unknown-freebsd12.0 Thread model: posix InstalledDir: /usr/bin
_OBJC_ALTCCVERSION_921dbbb2=none
ARCH=amd64
OPSYS=FreeBSD
_OSRELEASE=12.0-RELEASE-p10
OSREL=12.0
OSVERSION=1200086
PYTHONBASE=/usr/local
HAVE_COMPAT_IA32_KERN=YES
_SMP_CPUS=32
CONFIGURE_MAX_CMD_LEN=262144
HAVE_PORTS_ENV=1
#### Misc Poudriere ####
---End make.conf---
--Resource limits--
cpu time               (seconds, -t)  unlimited
file size           (512-blocks, -f)  unlimited
data seg size           (kbytes, -d)  33554432
stack size              (kbytes, -s)  524288
core file size      (512-blocks, -c)  unlimited
max memory size         (kbytes, -m)  unlimited
locked memory           (kbytes, -l)  unlimited
max user processes              (-u)  89999
open files                      (-n)  1024
virtual mem size        (kbytes, -v)  unlimited
swap limit              (kbytes, -w)  unlimited
socket buffer size       (bytes, -b)  unlimited
pseudo-terminals                (-p)  unlimited
kqueues                         (-k)  unlimited
umtx shared locks               (-o)  unlimited
--End resource limits--
=======================<phase: check-sanity   >============================
===>  License APACHE20 accepted by the user
===========================================================================
=======================<phase: pkg-depends    >============================
===>   libreSense-upgrade-0.69 depends on file: /usr/local/sbin/pkg - not found
===>   Installing existing package /packages/All/pkg-1.12.0.txz
[libreSense_master_amd64-libreSense_devel-job-03] Installing pkg-1.12.0...
[libreSense_master_amd64-libreSense_devel-job-03] Extracting pkg-1.12.0: .......... done
===>   libreSense-upgrade-0.69 depends on file: /usr/local/sbin/pkg - found
===>   Returning to build of libreSense-upgrade-0.69
===========================================================================
=======================<phase: fetch-depends  >============================
===========================================================================
=======================<phase: fetch          >============================
===>  License APACHE20 accepted by the user
===> Fetching all distfiles required by libreSense-upgrade-0.69 for building
===========================================================================
=======================<phase: checksum       >============================
===>  License APACHE20 accepted by the user
===> Fetching all distfiles required by libreSense-upgrade-0.69 for building
===========================================================================
=======================<phase: extract-depends>============================
===========================================================================
=======================<phase: extract        >============================
===>  License APACHE20 accepted by the user
===> Fetching all distfiles required by libreSense-upgrade-0.69 for building
===>  Extracting for libreSense-upgrade-0.69
cp -f -r /usr/ports/sysutils/libreSense-upgrade/files/* /wrkdirs/usr/ports/sysutils/libreSense-upgrade/work/libreSense-upgrade-0.69
===========================================================================
=======================<phase: patch-depends  >============================
===========================================================================
=======================<phase: patch          >============================
===>  Patching for libreSense-upgrade-0.69
===========================================================================
=======================<phase: build-depends  >============================
===========================================================================
=======================<phase: lib-depends    >============================
===========================================================================
=======================<phase: configure      >============================
===>  Configuring for libreSense-upgrade-0.69
===========================================================================
=======================<phase: build          >============================
===========================================================================
=======================<phase: run-depends    >============================
===========================================================================
=======================<phase: stage          >============================
===>  Staging for libreSense-upgrade-0.69
===>   Generating temporary packing list
/bin/mkdir -p /wrkdirs/usr/ports/sysutils/libreSense-upgrade/work/stage/usr/local/sbin
/bin/mkdir -p /wrkdirs/usr/ports/sysutils/libreSense-upgrade/work/stage/usr/local/libexec
install  -m 555 /wrkdirs/usr/ports/sysutils/libreSense-upgrade/work/libreSense-upgrade-0.69/libreSense-upgrade  /wrkdirs/usr/ports/sysutils/libreSense-upgrade/work/stage/usr/local/libexec
install  -m 555 /wrkdirs/usr/ports/sysutils/libreSense-upgrade/work/libreSense-upgrade-0.69/libreSense-upgrade.wrapper  /wrkdirs/usr/ports/sysutils/libreSense-upgrade/work/stage/usr/local/sbin/libreSense-upgrade
install: /wrkdirs/usr/ports/sysutils/libreSense-upgrade/work/libreSense-upgrade-0.69/libreSense-upgrade.wrapper: No such file or directory
*** Error code 71

Stop.
make: stopped in /usr/ports/sysutils/libreSense-upgrade
=>> Cleaning up wrkdir
===>  Cleaning for libreSense-upgrade-0.69
build of sysutils/libreSense-upgrade | libreSense-upgrade-0.69 ended at Thu Nov 14 17:11:13 PST 2019
build time: 00:00:02
!!! build failure encountered !!!
`

**Comment by tajummal-lab** [comment]
Yes, i tried this
You just need to rename files in sysutils/pfsense-upgrade but not the
pfsense-upgrade.
