### ISSUE TITLE
./build.sh --update-pkg-repo ERROR | php82-XXX-module-0.95: Failed: build

### ISSUE THREAD

**Issue by tuntin9x** [Augustin-FL/building-pfsense-iso-from-source#60]
![image](https://github.com/Augustin-FL/building-pfsense-iso-from-source/assets/42837549/69219e29-a30a-44a0-be4e-30c27b42ebeb)

php82-XXX-module-0.95: Failed: build

**Comment by tuntin9x** [comment]
Hello, I rebuilt according to the documentation but at the pkg build step I received the above error, please help

**Comment by Augustin-FL** [comment]
Hi,

As mentioned:
```
In case something goes wrong: Logs files can be seen using HTTP or directly on the build server, 
in the folder /usr/local/poudriere/data/logs/bulk/. 
You need to analyze the logs of each failed port to understand exactly what's the problem for each of them.
```

Does the log of the port display an error? if yes, which one?

**Comment by Augustin-FL** [comment]
I will close this issue, feel free to reopen it if needed
