### ISSUE TITLE
Error: Don’t know how to make aes-586.S 

### ISSUE THREAD

**Issue by sagarsec** [Augustin-FL/building-pfsense-iso-from-source#62]
![e81aaa47-43a2-480b-9797-226158b2e154](https://github.com/user-attachments/assets/bf99f756-4634-4eb9-bf9a-836d245321b0)

**Comment by Augustin-FL** [comment]
Could you try to merge https://github.com/pfsense/FreeBSD-src/pull/56 into your branch and confirm if it works?

(I haven't tested it, but it feel like the PR is related to your compilation error)

**Comment by sagarsec** [comment]
![image](https://github.com/user-attachments/assets/2db91d62-0b2e-48af-987c-c95b6746d658)


Please help getting the error in 
./build.sh --skip-final-rsync iso

**Comment by sagarsec** [comment]
Dear Augstin please help

**Comment by Augustin-FL** [comment]
indeed there was a mistake in the guidelines, thanks for pointing it out. 

Fyi, you didn't apply the patch correctly in builder_common.sh (you are missing at least [this line](https://github.com/Augustin-FL/building-pfsense-iso-from-source/blob/48c98dc2732f4fc12f5b45a6fb6d407704bffa45/patches/builder-common.sh.diff#L86)). You should probably have a look on how to use [`git apply` / `git am`](https://stackoverflow.com/questions/2249852/how-to-apply-a-patch-generated-with-git-format-patch).
