### ISSUE TITLE
after build kernal, iso not able to find iso file in /pfsense/tmp

### ISSUE THREAD

**Issue by tajummal-lab** [Augustin-FL/building-pfsense-iso-from-source#7]
yesterday system was restarted but FreeBSD ports was build after restart then i run command for building iso after that i`m not able to get iso file as you mention the path
/pfsense/tmp/${product_name}/installer

i think product_name was reset after restart because it gives "product_name undefined "
now i`m not able to find what the problem is?? where is the ISO file??
what steps will required again to build iso 
![123](https://user-images.githubusercontent.com/56956553/67736109-31a45580-fa28-11e9-9c25-4b6596dcc9c7.PNG)

**Comment by Augustin-FL** [comment]
Well that's quite simple
it mean that the script building the ISO failed before the end

please check logs and possibly re run the script to check the error

**Comment by tajummal-lab** [comment]
Yes sir ,but there no any data in /root/pfsense/log
I think this was because I restart the system and the variable was flush so
they giving me the error undefined error

What should we do, set variable and run ln command to link files again for
data logging and kernel building??

**Comment by tajummal-lab** [comment]
It is requested to highlight the steps we required to build the iso ,
dependencies and complete configuration files.
Because starting again from scratch is time consuming process.

And 1 suggestion ,that is kindly fix the set variable values instead of
saving in a variable because there may we require to restart machine so in
that scenario they cause problem.

**Comment by tajummal-lab** [comment]
@Augustin-FL 
an error occur after running ./build.sh --skip-final-rsync iso
![kernal_building_error](https://user-images.githubusercontent.com/56956553/67853440-cad87800-facb-11e9-8767-6bd498aea267.PNG)

**Comment by Augustin-FL** [comment]
this is expected 

see https://forums.freebsd.org/threads/error-while-compiling-release-11-custom-kernel-after-spectre-meltdown-updates.65555/

it is not critical

**Comment by Augustin-FL** [comment]
Closing this issue because there seems to be no problem here:

- If you restarted your build server, then you will indeed need to re-define variables (using `set`). 
I don't plan to update the tutorial for making these variables reboot-resistant : Is not asked to restart the build server in the tutorial.

- ctfconvert errors are perfectly fine and are non-critical.
