### ISSUE TITLE
Compressing kernel error : Unable to access file /root/MyFirewall/tmp/stage-dir/share/MyFirewall/fix_for_SA-19-10.ufs:No such file or directory

### ISSUE THREAD

**Issue by sreekupm** [Augustin-FL/building-pfsense-iso-from-source#8]
Dear Augustin,

Please help me. 

====>> Compressing kernel
>>> Cloning everything to /root/MyFirewall/tmp/stage-dir staging area...mv: rename /root/MyFirewall/tmp/stage-dir/usr/local/sbin/pfSense-upgrade to /root/MyFirewall/tmp/stage-dir/usr/local/sbin/MyFirewall-upgrade: No such file or directory
====>> Copying metadata for package rc
====>> Creating core package rc
pkg: Unable to access file /root/MyFirewall/tmp/stage-dir/share/MyFirewall/fix_for_SA-19-10.ufs:No such file or directory
====>> ERROR: Execution of 'pkg create -o /root/MyFirewall/tmp/MyFirewall_master_amd64-core/.real_20191103-0902/All -p /tmp/rc.FEKuT1R/rc_plist -r /root/MyFirewall/tmp/stage-dir -m /tmp/rc.FEKuT1R/rc_metadir' failed (rc = 70)
====>> Removing immutable flags from /tmp/rc.FEKuT1R
====>> Removing recursively /tmp/rc.FEKuT1R

**Comment by Augustin-FL** [comment]
Hello,
as mentioned previously, I updated the guidelines :

```
cd /root/pfsense

mv src/usr/local/share/pfSense src/usr/local/share/${product_name}
rm src/usr/local/share/${product_name}/keys/pkg/trusted/*
cp /root/sign/fingerprint src/usr/local/share/${product_name}/keys/pkg/trusted/fingerprint
```

**Comment by sreekupm** [comment]
tried more than 20 times getting the same error :(

**Comment by Augustin-FL** [comment]
What's your error when executing the command mv/rm/cp ?

**Comment by sreekupm** [comment]
no error

**Comment by sreekupm** [comment]
root@freebsd:~/pfsense #
root@freebsd:~/pfsense # mv src/usr/local/share/pfSense src/usr/local/share/${product_name}
mv: rename src/usr/local/share/pfSense to src/usr/local/share/MyFirewall/pfSense: No such file or directory
root@freebsd:~/pfsense # rm src/usr/local/share/${product_name}/keys/pkg/trusted/*
root@freebsd:~/pfsense # cp /root/sign/fingerprint src/usr/local/share/${product_name}/keys/pkg/trusted/fingerprint
root@freebsd:~/pfsense #

**Comment by Augustin-FL** [comment]
```
mv: rename src/usr/local/share/pfSense to src/usr/local/share/MyFirewall/pfSense: No such file or directory
```
No error, really?

At this point, your pfsense git tree seems corrupted.
I would recommend you to `rm -rf /root/pfsense` then to start over again with git clone

(no need to re-create a jail or to rebuild packages, since you are only removing the files from pfSense repo)

**Comment by sreekupm** [comment]
root@freebsd:~ # rm -rf /root/pfsense
rm: /root/pfsense/tmp/stage-dir/libexec/ld-elf.so.1: Operation not permitted
rm: /root/pfsense/tmp/stage-dir/libexec: Directory not empty
rm: /root/pfsense/tmp/stage-dir/var/empty: Operation not permitted
rm: /root/pfsense/tmp/stage-dir/var: Directory not empty
rm: /root/pfsense/tmp/stage-dir/sbin/init: Operation not permitted
rm: /root/pfsense/tmp/stage-dir/sbin: Directory not empty
rm: /root/pfsense/tmp/stage-dir/usr/lib/librt.so.1: Operation not permitted
rm: /root/pfsense/tmp/stage-dir/usr/lib: Directory not empty
rm: /root/pfsense/tmp/stage-dir/usr/bin/su: Operation not permitted
rm: /root/pfsense/tmp/stage-dir/usr/bin/crontab: Operation not permitted
rm: /root/pfsense/tmp/stage-dir/usr/bin/opiepasswd: Operation not permitted
rm: /root/pfsense/tmp/stage-dir/usr/bin/passwd: Operation not permitted
rm: /root/pfsense/tmp/stage-dir/usr/bin/chpass: Operation not permitted
rm: /root/pfsense/tmp/stage-dir/usr/bin/opieinfo: Operation not permitted
rm: /root/pfsense/tmp/stage-dir/usr/bin: Directory not empty
rm: /root/pfsense/tmp/stage-dir/usr: Directory not empty
rm: /root/pfsense/tmp/stage-dir/lib/libc.so.7: Operation not permitted
rm: /root/pfsense/tmp/stage-dir/lib/libthr.so.3: Operation not permitted
rm: /root/pfsense/tmp/stage-dir/lib/libcrypt.so.5: Operation not permitted
rm: /root/pfsense/tmp/stage-dir/lib: Directory not empty
rm: /root/pfsense/tmp/stage-dir: Directory not empty
rm: /root/pfsense/tmp/installer-dir/lib/libc.so.7: Operation not permitted
rm: /root/pfsense/tmp/installer-dir/lib/libcrypt.so.5: Operation not permitted
rm: /root/pfsense/tmp/installer-dir/lib/libthr.so.3: Operation not permitted
rm: /root/pfsense/tmp/installer-dir/lib: Directory not empty
rm: /root/pfsense/tmp/installer-dir/usr/lib/librt.so.1: Operation not permitted
rm: /root/pfsense/tmp/installer-dir/usr/lib: Directory not empty
rm: /root/pfsense/tmp/installer-dir/usr/bin/opieinfo: Operation not permitted
rm: /root/pfsense/tmp/installer-dir/usr/bin/su: Operation not permitted
rm: /root/pfsense/tmp/installer-dir/usr/bin/chpass: Operation not permitted
rm: /root/pfsense/tmp/installer-dir/usr/bin/opiepasswd: Operation not permitted
rm: /root/pfsense/tmp/installer-dir/usr/bin/crontab: Operation not permitted
rm: /root/pfsense/tmp/installer-dir/usr/bin/passwd: Operation not permitted
rm: /root/pfsense/tmp/installer-dir/usr/bin: Directory not empty
rm: /root/pfsense/tmp/installer-dir/usr: Directory not empty
rm: /root/pfsense/tmp/installer-dir/sbin/init: Operation not permitted
rm: /root/pfsense/tmp/installer-dir/sbin: Directory not empty
rm: /root/pfsense/tmp/installer-dir/var/empty: Operation not permitted
rm: /root/pfsense/tmp/installer-dir/var: Directory not empty
rm: /root/pfsense/tmp/installer-dir/libexec/ld-elf.so.1: Operation not permitted
rm: /root/pfsense/tmp/installer-dir/libexec: Directory not empty
rm: /root/pfsense/tmp/installer-dir: Directory not empty
rm: /root/pfsense/tmp: Directory not empty
rm: /root/pfsense: Directory not empty
root@freebsd:~ #

**Comment by sreekupm** [comment]
Again Same Error :( 

====>> Compressing kernel
>>> Cloning everything to /root/pfsense/tmp/stage-dir staging area...mv: rename /root/pfsense/tmp/stage-dir/usr/local/sbin/pfSense-upgrade to /root/pfsense/tmp/stage-dir/usr/local/sbin/MyFirewall-upgrade: No such file or directory
====>> Copying metadata for package rc
====>> Creating core package rc
pkg: Unable to access file /root/pfsense/tmp/stage-dir/share/MyFirewall/fix_for_SA-19-10.ufs:No such file or directory
====>> ERROR: Execution of 'pkg create -o /root/pfsense/tmp/MyFirewall_master_amd64-core/.real_20191104-0000/All -p /tmp/rc.OaH5N1Q/rc_plist -r /root/pfsense/tmp/stage-dir -m /tmp/rc.OaH5N1Q/rc_metadir' failed (rc = 70)
====>> Removing immutable flags from /tmp/rc.OaH5N1Q
====>> Removing recursively /tmp/rc.OaH5N1Q

####################################
Something went wrong, check errors!
####################################

**Comment by sreekupm** [comment]
Dear Augustin, 

Tried lots of times :(

**Comment by Augustin-FL** [comment]
Dear 

Issues are here not for for asking for help, but for reporting bugs

- What's inside the folder ```/root/pfsense/tmp/stage-dir/share/```
- Did you tried to restart from ground zero? (reinstall freebsd, etc?).

**Comment by sreekupm** [comment]
What's inside the folder /root/pfsense/tmp/stage-dir/share/  --> share folder is not exist.

Did you tried to restart from ground zero? (reinstall freebsd, etc?).   **yes more than 25 times**

**Comment by Augustin-FL** [comment]
what's the content of `/root/pfsense/src/usr/local/share/` ?

**Comment by sreekupm** [comment]
Share folder is not in local folder

**Comment by Augustin-FL** [comment]
> Share folder is not in local folder

then it means you messed up with the git clone or with the `share` folder itself

https://github.com/pfsense/pfsense/tree/master/src/usr/local

there is a folder share in src/usr/local on pfSense repository. please check why this folder disappeared from your system.

closing this issue as it seems an user error (share folder deleted by mistake or git clone failure)
